import Link from "next/link";
import { AppHeader, AppShell, BottomNavigation } from "@/components/ui/app-shell";
import { Icon } from "@/components/ui/icons";
import { Card, SectionHeader } from "@/components/ui/primitives";
import { Today } from "@/components/app/today";
import { Planning } from "@/components/app/planning";
import { ShoppingCash } from "@/components/app/shopping-cash";
import { ChildrenPanel } from "@/components/app/children-panel";
import { TeamPanel } from "@/components/app/team-panel";
import { RulesPanel } from "@/components/app/rules-panel";
import { MoreHub } from "@/components/app/more-hub";
import { getDemoData } from "@/lib/demo-data";
import { normalizeMoreArea, normalizeSection, visiblePrimaryNav, type V4MoreArea } from "@/lib/v4-navigation";
import { sectionDate } from "@/lib/coherence";
import type { members } from "@/db/schema";

type Caregiver="nora"|"sophie";type Member=typeof members.$inferSelect;
function DemoUtilityPanel({area}:{area:V4MoreArea}){
  if(area==="messages")return <Card><SectionHeader title="Messages" eyebrow="Démo · lecture seule"/><div className="v57-demo-placeholder"><div className="v57-demo-placeholder-row"><span><Icon name="people" size={17}/></span><span><strong>Nora · 15:18</strong><small>Bien arrivées au parc. Lina a pris son goûter avant de partir.</small></span></div><div className="v57-demo-placeholder-row"><span><Icon name="child" size={17}/></span><span><strong>Camille · 15:20</strong><small>Super, merci. Le bonnet de piscine est bien dans le sac bleu.</small></span></div></div></Card>;
  if(area==="reports")return <Card><SectionHeader title="Heures & export" eyebrow="Exemple mensuel"/><div className="v57-demo-placeholder"><div className="v57-demo-placeholder-row"><span><Icon name="clock" size={17}/></span><span><strong>Nora · 36 h 30</strong><small>Gardes planifiées et réalisées du mois, regroupées pour faciliter le récapitulatif.</small></span></div><div className="v57-demo-placeholder-row"><span><Icon name="calendar" size={17}/></span><span><strong>Export mensuel</strong><small>Dans l’application réelle, le parent peut récupérer un récapitulatif exploitable sans ressaisir chaque journée.</small></span></div></div></Card>;
  if(area==="settings")return <Card><SectionHeader title="Réglages" eyebrow="Notifications & données"/><div className="v57-demo-placeholder"><div className="v57-demo-placeholder-row"><span><Icon name="bell" size={17}/></span><span><strong>Notifications</strong><small>Choisir les alertes utiles, notamment les changements de Planning.</small></span></div><div className="v57-demo-placeholder-row"><span><Icon name="settings" size={17}/></span><span><strong>Vos données</strong><small>Exporter les informations liées au compte ou demander sa suppression.</small></span></div></div></Card>;
  return null;
}
export default async function DemoPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const params=await searchParams;const data=getDemoData();const previewCaregiver:Caregiver|undefined=params.preview===data.sophie.id?"sophie":params.preview===data.nora.id?"nora":undefined;const role=params.role==="nanny"||previewCaregiver?"nanny":"parent";const caregiver:Caregiver=previewCaregiver||(params.caregiver==="sophie"?"sophie":"nora");const viewMembership=role==="parent"?data.parent:caregiver==="sophie"?data.sophie:data.nora;const snapshot=role==="parent"?data.parentSnapshot:caregiver==="sophie"?data.sophieSnapshot:data.noraSnapshot;const canShopping=role==="parent"||caregiver==="nora";const section=normalizeSection(params.section,true,canShopping);const rawArea=normalizeMoreArea(params.section,params.area);const area:V4MoreArea=rawArea==="history"?"home":rawArea;const selectedDate=sectionDate(section,params.date||data.date,data.date);const memberName=(member:Member)=>data.names.get(member.id)||member.label||member.role;const q=(extra:Record<string,string>)=>{let nextRole=role,nextCaregiver=caregiver;if(extra.preview===data.nora.id){nextRole="nanny";nextCaregiver="nora";}if(extra.preview===data.sophie.id){nextRole="nanny";nextCaregiver="sophie";}const query=new URLSearchParams({role:nextRole,...(nextRole==="nanny"?{caregiver:nextCaregiver}:{}),date:selectedDate});for(const [key,value] of Object.entries(extra)){if(key==="preview")continue;if(value)query.set(key,value);else query.delete(key);}return `/demo?${query}`;};const navItems=visiblePrimaryNav({canPlanning:true,canShopping});const nav=navItems.map(item=>({id:item.id,label:item.label,icon:item.icon,href:q({section:item.id,date:sectionDate(item.id,selectedDate,data.date)})}));const roleSwitch=<div className="v57-demo-role-switch"><Link className={role==="parent"?"is-active":""} href="/demo?role=parent&section=today"><Icon name="child" size={15}/> Parent</Link><Link className={role==="nanny"&&caregiver==="nora"?"is-active":""} href="/demo?role=nanny&caregiver=nora&section=today"><Icon name="people" size={15}/> Nora · nounou</Link><Link className={role==="nanny"&&caregiver==="sophie"?"is-active":""} href="/demo?role=nanny&caregiver=sophie&section=today"><Icon name="moon" size={15}/> Sophie · baby-sitter</Link></div>;const shoppingQ=(extra:Record<string,string>)=>q({...extra,section:"shopping",area:""});
  return <AppShell header={<AppHeader spaceName="Nanny Youpiii" context={`Démo · ${role==="parent"?"Parent":memberName(viewMembership)}`} action={<div className="v57-demo-header-actions"><Link href="/" className="v4-text-action">← Site</Link><Link href="/auth/sign-up" className="btn brandbtn v57-demo-create">Créer mon espace</Link></div>}/>} navigation={<BottomNavigation items={nav} activeId={section}/> }>
    <div className="v57-demo-wrap"><section className="v57-demo-intro"><div className="v57-demo-intro-top"><div><span className="v57-demo-badge"><Icon name="eye" size={14}/> Démo interactive · aucune donnée réelle</span><h2>Testez Youpiii des deux côtés.</h2><p>Changez de rôle pour voir ce que le parent, la nounou de journée et la baby-sitter voient avec leurs propres accès. La démo est volontairement en lecture seule.</p></div></div>{roleSwitch}<div className="v57-demo-steps"><div className="v57-demo-step"><strong>Aujourd’hui</strong>Comprendre la journée</div><div className="v57-demo-step"><strong>Planning</strong>Préparer activités & gardes</div><div className="v57-demo-step"><strong>Courses</strong>Liste, caisse, avances</div><div className="v57-demo-step"><strong>Plus</strong>Équipe, consignes, réglages</div></div></section>
      {section==="planning"&&role==="parent"&&<div className="v57-demo-note"><h3>Le Planning est désormais le centre de toute l’organisation.</h3><p>Dans un vrai espace parent, c’est ici que vous créez les horaires de garde réguliers et ponctuels, les activités et les routines. Équipe & accès ne sert plus à gérer les horaires.</p><div className="v57-demo-mini-grid"><span>Horaires réguliers + exceptions</span><span>Routines réutilisables</span><span>Notifications à la nounou</span></div></div>}
      {section==="today"&&role==="nanny"&&<div className="v57-demo-note"><h3>La nounou peut garder le téléphone dans la poche.</h3><p>Commencer la garde est facultatif. Elle peut consulter sa journée, ajouter un moment utile après coup et faire un retour de fin de garde seulement si elle en a besoin.</p></div>}
    </div>
    {section==="today"&&<Today spaceId={data.space.id} selectedDate={data.date} snapshot={snapshot} memberName={memberName} actualMembership={viewMembership} viewMembership={viewMembership} parent={role==="parent"} preview={false} readOnly q={q} fullTeam={data.team} userFirstName={role==="parent"?"Camille":""} canActProgram={false} canActTasks={false} timezone={data.space.timezone}/>} 
    {section==="planning"&&<Planning spaceId={data.space.id} selectedDate={data.date} snapshot={snapshot} caregivers={role==="parent"?[data.nora,data.sophie]:[viewMembership]} children={snapshot.children} routines={role==="parent"?data.routines:[]} memberName={memberName} canActProgram={false} canActTasks={false} canManageSchedule={false} q={q} timezone={data.space.timezone}/>} 
    {section==="shopping"&&canShopping&&<ShoppingCash spaceId={data.space.id} snapshot={snapshot} team={data.team} children={snapshot.children} memberName={memberName} viewMembership={viewMembership} parent={role==="parent"} canAdd={false} canPurchase={false} canSeeCash={Boolean(snapshot.cash)} canManageCash={false} q={shoppingQ}/>} 
    {section==="more"&&area==="home"&&<MoreHub q={q} parent={role==="parent"} canChildren={role==="parent"} canTeam={role==="parent"} canRules={role==="parent"} canJournal personalTools/>} 
    {section==="more"&&area==="children"&&role==="parent"&&<ChildrenPanel spaceId={data.space.id} children={data.children} canEdit={false} q={q}/>} 
    {section==="more"&&area==="team"&&role==="parent"&&<TeamPanel spaceId={data.space.id} team={data.team} children={data.children} invitations={[]} memberName={memberName} selectedDate={data.date} q={q} scheduleRules={data.scheduleRules} memberChildLinks={data.memberChildLinks} canAdmin={false} previewableMemberIds={new Set([data.nora.id,data.sophie.id])}/>} 
    {section==="more"&&area==="rules"&&role==="parent"&&<RulesPanel spaceId={data.space.id} snapshot={data.parentSnapshot} team={data.team} routines={[]} canManage={false} q={q}/>} 
    {section==="more"&&(area==="shopping"||area==="cash")&&canShopping&&<ShoppingCash spaceId={data.space.id} snapshot={snapshot} team={data.team} children={snapshot.children} memberName={memberName} viewMembership={viewMembership} parent={role==="parent"} canAdd={false} canPurchase={false} canSeeCash={Boolean(snapshot.cash)} canManageCash={false} q={q}/>} 
    {section==="more"&&(area==="messages"||area==="reports"||area==="settings")&&<DemoUtilityPanel area={area}/>} 
    {section==="more"&&area==="home"&&role==="nanny"&&caregiver==="sophie"&&<Card tone="soft"><div className="v4-list-row"><span className="v4-row-icon"><Icon name="settings"/></span><span className="v4-row-copy"><strong>Accès minimal</strong><small>Sophie voit uniquement les rubriques autorisées pour Lina.</small></span></div></Card>}
  </AppShell>;
}
