import Link from "next/link";

const parentNav=[["today","Aujourd’hui"],["planning","Planning"],["shopping","Courses & caisse"],["config","Configuration"]] as const;
const nannyNav=[["today","Aujourd’hui"],["planning","Planning"],["shopping","Courses & caisse"]] as const;

function DemoHeader({role}:{role:string}){return <><div className="demo-banner"><span>Mode démo · aucune donnée réelle</span><Link className="btn primary" href="/auth/sign-up">Créer mon compte</Link></div><header className="top"><div className="topin"><Link className="brand" href="/"><div className="logo">Y!</div><div><div>Nanny Youpiii</div><small className="muted">Famille Démo</small></div></Link><div className="tabs demo-role-tabs"><Link className={role==="parent"?"active":""} href="/demo?role=parent&section=today">Parent</Link><Link className={role==="nanny"?"active":""} href="/demo?role=nanny&section=today">Nounou</Link></div></div></header></>}

function TodayParent(){return <div className="stack"><section className="hero"><div className="eyebrow">Vue parent</div><h1>Bonjour Camille</h1><p className="muted">Tout ce qu’il faut comprendre aujourd’hui en quelques secondes.</p><div className="row wrap" style={{marginTop:16}}><span className="pill green">Nora · 08:30–18:00</span><span className="pill green">Sophie · 18:00–22:30</span></div></section><div className="grid"><div className="stack"><section className="card"><div className="sectiontitle">Aujourd’hui avec Lina</div><div className="list"><div className="item"><div><strong>10:00 · Parc</strong><small>Sortie avec Nora</small></div><span className="pill green">Fait</span></div><div className="item"><div><strong>12:15 · Déjeuner</strong><small>Poulet, riz et courgettes</small></div><span className="pill">Prévu</span></div><div className="item"><div><strong>15:30 · Piscine</strong><small>Bonnet dans le sac bleu</small></div><span className="pill">Prévu</span></div></div></section><section className="card"><div className="sectiontitle">Équipe aujourd’hui</div><div className="list"><div className="item"><strong>Nora · Nounou</strong><span>08:30–18:00</span></div><div className="item"><strong>Sophie · Baby-sitter</strong><span>18:00–22:30</span></div></div></section></div><div className="stack"><section className="card money"><div className="sectiontitle">Caisse</div><div className="metric">85,30 €</div><div className="muted">disponibles</div><div className="divider"/><b>À rembourser à Nora : 5,00 €</b></section><section className="card"><div className="sectiontitle">Courses</div><div className="metric smallmetric">3</div><div className="muted">produits à acheter</div></section><section className="card"><div className="sectiontitle">Important aujourd’hui</div><div className="list"><div className="item"><strong>⚠️ Bonnet pour la piscine</strong></div><div className="item"><strong>🚫 Pas de vidéos</strong></div></div></section></div></div></div>}

function TodayNanny(){return <div className="stack"><section className="hero"><div className="eyebrow">Vue nounou</div><h1>Bonjour Nora</h1><p className="muted">Uniquement ce qui vous concerne aujourd’hui.</p><div className="row wrap" style={{marginTop:16}}><span className="pill green">Lina · 08:30–18:00</span></div></section><section className="card"><div className="sectiontitle">Important aujourd’hui</div><div className="list"><div className="item"><strong>⚠️ Penser au bonnet pour la piscine</strong></div><div className="item"><strong>🚫 Pas de vidéos</strong></div><div className="item"><strong>🎧 Lunii autorisée</strong></div></div></section><div className="grid"><section className="card"><div className="sectiontitle">Programme</div><div className="list"><div className="item status-DONE"><div><strong>10:00 · Parc</strong><small>Réalisé</small></div><span className="pill green">Fait</span></div><div className="item"><div><strong>12:15 · Déjeuner</strong><small>Réchauffer le plat au réfrigérateur</small></div><span className="pill">Ensuite</span></div><div className="item"><div><strong>15:30 · Piscine</strong><small>Sac bleu dans l’entrée</small></div><span className="pill">Prévu</span></div></div></section><section className="card"><div className="sectiontitle">À acheter</div><div className="list"><div className="item"><strong>Yaourts x4</strong><span className="pill">À acheter</span></div><div className="item"><strong>Compotes</strong><span className="pill">À acheter</span></div></div><div className="divider"/><div className="row between"><span>Caisse disponible</span><b>85,30 €</b></div></section></div></div>}

function PlanningDemo({role}:{role:string}){return <div className="stack"><div><div className="eyebrow">Planning étendu</div><h1>Planning</h1><p className="muted">Historique et jours à venir dans le même écran.</p></div><section className="card planningbar"><div className="row between wrap"><button className="btn soft" disabled>− 7 j</button><div><div className="eyebrow">À venir</div><b>Mercredi 12 août</b></div><button className="btn soft" disabled>+ 7 j</button></div></section><div className="grid"><section className="card"><div className="sectiontitle">Programme</div><div className="list"><div className="item"><div><strong>09:00 · École</strong><small>Lina</small></div><span className="pill">Prévu</span></div><div className="item"><div><strong>12:00 · Déjeuner</strong><small>Pâtes, tomates, fromage</small></div><span className="pill">Prévu</span></div><div className="item"><div><strong>16:00 · Parc</strong><small>{role==="parent"?"Lina · Nora":"Avec Lina"}</small></div><span className="pill">Prévu</span></div></div></section><section className="card"><div className="sectiontitle">Tâches</div><div className="list"><div className="item"><strong>Préparer le sac de piscine</strong><span className="pill">À faire</span></div><div className="item"><strong>Mettre les compotes au frais</strong><span className="pill">À faire</span></div></div></section></div></div>}

function ShoppingDemo({role}:{role:string}){return <div className="stack"><div><div className="eyebrow">Une seule chaîne</div><h1>Courses & caisse</h1><p className="muted">Le produit acheté et son prix mettent automatiquement la caisse à jour.</p></div><section className="card shopcash-hero"><div><div className="eyebrow">Caisse disponible</div><div className="metric">85,30 €</div></div>{role==="nanny"&&<div><div className="eyebrow">À vous rembourser</div><div className="metric smallmetric">5,00 €</div></div>}<div><div className="eyebrow">À acheter</div><div className="metric smallmetric">3</div></div></section><div className="grid"><section className="card"><div className="sectiontitle">À acheter</div><div className="list"><div className="item purchase-item"><div><strong>Yaourts x4</strong><small>Pour le goûter</small></div>{role==="nanny"?<div className="purchase-action"><label className="price-field"><span>Prix</span><input placeholder="€" disabled/></label><button className="btn primary" disabled>Acheté ✓</button></div>:<span className="pill">À acheter</span>}</div><div className="item purchase-item"><div><strong>Compotes</strong><small>Sans sucre ajouté</small></div>{role==="nanny"?<div className="purchase-action"><label className="price-field"><span>Prix</span><input placeholder="€" disabled/></label><button className="btn primary" disabled>Acheté ✓</button></div>:<span className="pill">À acheter</span>}</div></div></section><section className="card"><div className="sectiontitle">Achats enregistrés</div><div className="list"><div className="item"><div><strong>Achat · Lait</strong><small>Nora</small></div><b>3,20 €</b></div><div className="item"><div><strong>Achat · Crème solaire</strong><small>Nora</small></div><b>11,50 €</b></div></div></section></div></div>}

function ConfigDemo(){return <div className="stack"><div><div className="eyebrow">Configuration parent</div><h1>Enfants & équipe</h1><p className="muted">Le parent choisit précisément qui voit quoi.</p></div><div className="grid"><section className="card"><div className="sectiontitle">Enfants</div><div className="list"><div className="item"><div><strong>Lina</strong><small>5 ans</small></div></div><div className="item"><div><strong>Jules</strong><small>2 ans</small></div></div></div></section><section className="card"><div className="sectiontitle">Équipe</div><div className="list"><div className="item"><div><strong>Nora</strong><small>Nounou · Lina + Jules</small></div><Link className="btn soft" href="/demo?role=nanny&section=today">Voir comme</Link></div><div className="item"><div><strong>Sophie</strong><small>Baby-sitter · Lina</small></div><span className="pill">Soir</span></div></div></section></div><section className="card"><div className="sectiontitle">Attributions de Nora</div><div className="checkgrid"><span className="checkrow">✓ Lina</span><span className="checkrow">✓ Jules</span><span className="checkrow">✓ Planning</span><span className="checkrow">✓ Tâches</span><span className="checkrow">✓ Courses & achats</span><span className="checkrow">✓ Caisse</span><span className="checkrow">✓ Journal</span></div></section></div>}

export default async function DemoPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const params=await searchParams;
  const role=params.role==="nanny"?"nanny":"parent";
  const nav=role==="parent"?parentNav:nannyNav;
  const requested=params.section||"today";
  const section=nav.some(([id])=>id===requested)?requested:"today";
  const href=(id:string)=>`/demo?role=${role}&section=${id}`;
  return <div className="shell demo-shell"><DemoHeader role={role}/><main className="main">{section==="today"&&(role==="parent"?<TodayParent/>:<TodayNanny/>)}{section==="planning"&&<PlanningDemo role={role}/>} {section==="shopping"&&<ShoppingDemo role={role}/>} {section==="config"&&role==="parent"&&<ConfigDemo/>}</main><nav className="nav demo-nav">{nav.map(([id,label])=><Link key={id} className={section===id?"active":""} href={href(id)}>{label}</Link>)}</nav></div>
}
