"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { and, eq } from "drizzle-orm";
import { db } from "@/db";
import * as s from "@/db/schema";
import { assertChildren, text } from "@/lib/action-helpers";
import { activityDefinition, activityKeyFromStored } from "@/lib/activity";
import { isParentRole, requirePermission } from "@/lib/security";
import { notifySpaceUsers, trackProductEvent } from "@/lib/notifications";

function safeReturnTo(formData:FormData){const value=text(formData,"returnTo");return value.startsWith("/app?")?value:"/app";}
async function spaceClock(spaceId:string){const [space]=await db.select({timezone:s.careSpaces.timezone}).from(s.careSpaces).where(eq(s.careSpaces.id,spaceId)).limit(1);if(!space)throw new Error("Espace introuvable");const parts=new Intl.DateTimeFormat("fr-CA",{timeZone:space.timezone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date());const get=(type:Intl.DateTimeFormatPartTypes)=>parts.find(part=>part.type===type)?.value||"";return {date:`${get("year")}-${get("month")}-${get("day")}`,time:`${get("hour")}:${get("minute")}`};}
function choice(formData:FormData){const raw=text(formData,"activityType")||"OTHER";if(raw==="OTHER"){const title=text(formData,"customTitle").trim().replace(/\s+/g," ").slice(0,80);if(!title)throw new Error("Nommez l’activité");return {key:activityKeyFromStored("",title),title};}if(raw.startsWith("PRESET::")||raw.startsWith("CURRENT::")){const title=raw.slice(raw.indexOf("::")+2).trim().slice(0,80);if(!title)throw new Error("Activité invalide");return {key:activityKeyFromStored("",title),title};}const definition=activityDefinition(raw);return {key:definition.key,title:definition.label};}
export async function addCaregiverActivityAction(formData:FormData){
  const spaceId=text(formData,"spaceId");const {session,membership}=await requirePermission(spaceId,"program");if(isParentRole(membership.role))throw new Error("FORBIDDEN");const clock=await spaceClock(spaceId);const date=text(formData,"date")||clock.date;const time=text(formData,"time")||clock.time;if(date>clock.date||(date===clock.date&&time>clock.time))throw new Error("Une activité réalisée ne peut pas être dans le futur");const selected=choice(formData);const definition=activityDefinition(selected.key);const childIds=[...new Set(formData.getAll("childIds").map(String).filter(Boolean))];await assertChildren(membership.id,childIds);const now=new Date();const [item]=await db.insert(s.programItems).values({careSpaceId:spaceId,programDate:date,type:definition.label,title:selected.title,description:text(formData,"description")||null,plannedStart:time,status:"DONE",createdBy:session.user.id,completedByMemberId:membership.id,completedAt:now}).returning({id:s.programItems.id});if(childIds.length)await db.insert(s.programChildren).values(childIds.map(childId=>({programItemId:item.id,childId})));await db.insert(s.programAssignees).values({programItemId:item.id,memberId:membership.id}).onConflictDoNothing();await db.insert(s.activityLogs).values({careSpaceId:spaceId,actorUserId:session.user.id,action:"ACTIVITY_CREATED_RETROACTIVE",entityType:"program_item",entityId:item.id,metadata:{type:selected.key,date,time}});await trackProductEvent("ACTIVITY_CREATED",session.user.id,spaceId,{status:"DONE",type:selected.key,retroactive:date<clock.date||time<clock.time});await notifySpaceUsers({spaceId,excludeUserId:session.user.id,kind:"activities",type:"ACTIVITY_DONE",title:selected.title,body:text(formData,"description")||`Ajouté à ${time}`,url:`/app?space=${spaceId}&section=today`,childIds});revalidatePath("/app");redirect(safeReturnTo(formData));
}
