"use server";
import { revalidatePath } from "next/cache";
import { and, asc, eq, inArray } from "drizzle-orm";
import { db } from "@/db";
import * as s from "@/db/schema";
import { assertChildren, assertMembers, assertMembersCanAccessChildren, text } from "@/lib/action-helpers";
import { isParentRole, requirePermission } from "@/lib/security";
import { trackProductEvent } from "@/lib/notifications";
async function parentPermission(spaceId:string,permission:string){const ctx=await requirePermission(spaceId,permission);if(!isParentRole(ctx.membership.role))throw new Error("FORBIDDEN");return ctx;}
export async function updateChildAction(formData:FormData){const spaceId=text(formData,"spaceId"),childId=text(formData,"childId");const {session,membership}=await parentPermission(spaceId,"children");await assertChildren(membership.id,[childId]);await db.update(s.children).set({firstName:text(formData,"firstName"),birthDate:text(formData,"birthDate")||null,school:text(formData,"school")||null,allergies:text(formData,"allergies")||null,habits:text(formData,"habits")||null,emergencyContacts:text(formData,"emergencyContacts")||null,notes:text(formData,"notes")||null}).where(and(eq(s.children.id,childId),eq(s.children.careSpaceId,spaceId)));await trackProductEvent("CHILD_UPDATED",session.user.id,spaceId);revalidatePath("/app");}
export async function updateInstructionAction(formData:FormData){const spaceId=text(formData,"spaceId"),instructionId=text(formData,"instructionId");const {session,membership}=await parentPermission(spaceId,"journal");const childIds=formData.getAll("childIds").map(String),memberIds=formData.getAll("memberIds").map(String);await assertChildren(membership.id,childIds);await assertMembers(spaceId,memberIds);await assertMembersCanAccessChildren(spaceId,memberIds,childIds);await db.update(s.instructions).set({kind:text(formData,"kind") as typeof s.instructionKind.enumValues[number],text:text(formData,"text"),validOn:text(formData,"validOn")||null,permanent:!text(formData,"validOn"),childIds,memberIds}).where(and(eq(s.instructions.id,instructionId),eq(s.instructions.careSpaceId,spaceId)));await trackProductEvent("INSTRUCTION_UPDATED",session.user.id,spaceId);revalidatePath("/app");}
export async function deleteInstructionAction(formData:FormData){const spaceId=text(formData,"spaceId"),instructionId=text(formData,"instructionId");const {session}=await parentPermission(spaceId,"journal");await db.delete(s.instructions).where(and(eq(s.instructions.id,instructionId),eq(s.instructions.careSpaceId,spaceId)));await trackProductEvent("INSTRUCTION_DELETED",session.user.id,spaceId);revalidatePath("/app");}
export async function updateRoutineAction(formData:FormData){const spaceId=text(formData,"spaceId"),routineId=text(formData,"routineId");const {session}=await parentPermission(spaceId,"tasks");const [routine]=await db.select().from(s.routines).where(and(eq(s.routines.id,routineId),eq(s.routines.careSpaceId,spaceId))).limit(1);if(!routine)throw new Error("ROUTINE_NOT_FOUND");const lines=text(formData,"items").split("\n").map(value=>value.trim()).filter(Boolean);await db.transaction(async tx=>{await tx.update(s.routines).set({name:text(formData,"name"),description:text(formData,"description")||null}).where(eq(s.routines.id,routineId));await tx.delete(s.routineItems).where(eq(s.routineItems.routineId,routineId));if(lines.length)await tx.insert(s.routineItems).values(lines.map((title,position)=>({routineId,title,position})));});await trackProductEvent("ROUTINE_UPDATED",session.user.id,spaceId);revalidatePath("/app");}
export async function deleteRoutineAction(formData:FormData){const spaceId=text(formData,"spaceId"),routineId=text(formData,"routineId");const {session}=await parentPermission(spaceId,"tasks");await db.delete(s.routines).where(and(eq(s.routines.id,routineId),eq(s.routines.careSpaceId,spaceId)));await trackProductEvent("ROUTINE_DELETED",session.user.id,spaceId);revalidatePath("/app");}
function addMinutes(time:string,minutes:number){if(!time)return null;const [h,m]=time.split(":").map(Number);const total=(h*60+m+minutes)%(24*60);return `${String(Math.floor(total/60)).padStart(2,"0")}:${String(total%60).padStart(2,"0")}`;}
async function chooseCaregiver(spaceId:string,childId:string,requested:string){if(requested)return requested;const caregivers=(await db.select().from(s.members).where(and(eq(s.members.careSpaceId,spaceId),eq(s.members.status,"ACTIVE")))).filter(member=>!isParentRole(member.role));if(!caregivers.length)return "";if(!childId)return caregivers[0].id;const links=await db.select().from(s.memberChildren).where(and(inArray(s.memberChildren.memberId,caregivers.map(member=>member.id)),eq(s.memberChildren.childId,childId)));return caregivers.find(member=>links.some(link=>link.memberId===member.id))?.id||"";}
export async function applyRoutineToPlanningAction(formData:FormData){const spaceId=text(formData,"spaceId"),routineId=text(formData,"routineId"),date=text(formData,"date"),childId=text(formData,"childId"),start=text(formData,"start");const {session,membership}=await parentPermission(spaceId,"program");if(childId)await assertChildren(membership.id,[childId]);const memberId=await chooseCaregiver(spaceId,childId,text(formData,"memberId"));if(memberId){await assertMembers(spaceId,[memberId]);if(childId)await assertMembersCanAccessChildren(spaceId,[memberId],[childId]);}const [routine]=await db.select().from(s.routines).where(and(eq(s.routines.id,routineId),eq(s.routines.careSpaceId,spaceId))).limit(1);if(!routine)throw new Error("ROUTINE_NOT_FOUND");const items=await db.select().from(s.routineItems).where(eq(s.routineItems.routineId,routineId)).orderBy(asc(s.routineItems.position));await db.transaction(async tx=>{for(const [index,item] of items.entries()){const [created]=await tx.insert(s.programItems).values({careSpaceId:spaceId,programDate:date,type:"Routine",title:item.title,description:item.description,plannedStart:addMinutes(start,index*15),createdBy:session.user.id}).returning({id:s.programItems.id});if(childId)await tx.insert(s.programChildren).values({programItemId:created.id,childId});if(memberId)await tx.insert(s.programAssignees).values({programItemId:created.id,memberId});}});await trackProductEvent("ROUTINE_APPLIED",session.user.id,spaceId,{routineId,count:items.length});revalidatePath("/app");}
async function shoppingContext(spaceId:string,itemId:string){const [list]=await db.select().from(s.shoppingLists).where(and(eq(s.shoppingLists.careSpaceId,spaceId),eq(s.shoppingLists.active,true))).limit(1);if(!list)throw new Error("SHOPPING_LIST_NOT_FOUND");const [item]=await db.select().from(s.shoppingItems).where(and(eq(s.shoppingItems.id,itemId),eq(s.shoppingItems.shoppingListId,list.id))).limit(1);if(!item)throw new Error("SHOPPING_ITEM_NOT_FOUND");return item;}
export async function updateShoppingItemAction(formData:FormData){const spaceId=text(formData,"spaceId"),itemId=text(formData,"itemId");const {session,membership}=await requirePermission(spaceId,"shopping");const item=await shoppingContext(spaceId,itemId);if(item.status!=="TODO")throw new Error("Un achat terminé ne peut plus être modifié");const childId=text(formData,"childId")||null;if(childId)await assertChildren(membership.id,[childId]);await db.update(s.shoppingItems).set({name:text(formData,"name"),quantity:text(formData,"quantity")||null,comment:text(formData,"comment")||null,childId}).where(eq(s.shoppingItems.id,itemId));await trackProductEvent("SHOPPING_ITEM_UPDATED",session.user.id,spaceId);revalidatePath("/app");}
export async function deleteShoppingItemAction(formData:FormData){const spaceId=text(formData,"spaceId"),itemId=text(formData,"itemId");const {session}=await requirePermission(spaceId,"shopping");const item=await shoppingContext(spaceId,itemId);if(item.status!=="TODO")throw new Error("Un achat terminé ne peut plus être supprimé");await db.delete(s.shoppingItems).where(eq(s.shoppingItems.id,itemId));await trackProductEvent("SHOPPING_ITEM_DELETED",session.user.id,spaceId);revalidatePath("/app");}
