"use server";
import { revalidatePath } from "next/cache";
import { and, eq } from "drizzle-orm";
import { db } from "@/db";
import * as s from "@/db/schema";
import { assertChildren, assertMembers, assertMembersCanAccessChildren, assertWithinCareWindow, text, today } from "@/lib/action-helpers";
import { localDateTime } from "@/lib/coherence";
import { isParentRole, requirePermission } from "@/lib/security";
import { notifySpaceUsers, trackProductEvent } from "@/lib/notifications";
async function requireParentPermission(spaceId:string,permission:string){const ctx=await requirePermission(spaceId,permission);if(!isParentRole(ctx.membership.role))throw new Error("FORBIDDEN");return ctx;}
async function spaceToday(spaceId:string){const [space]=await db.select({timezone:s.careSpaces.timezone}).from(s.careSpaces).where(eq(s.careSpaces.id,spaceId)).limit(1);if(!space)throw new Error("Espace introuvable");return today(space.timezone);}
export async function addInstructionAction(formData:FormData){const spaceId=text(formData,"spaceId");const {session,membership}=await requireParentPermission(spaceId,"journal");const childIds=formData.getAll("childIds").map(String);const memberIds=formData.getAll("memberIds").map(String);await assertChildren(membership.id,childIds);await assertMembers(spaceId,memberIds);await assertMembersCanAccessChildren(spaceId,memberIds,childIds);await db.insert(s.instructions).values({careSpaceId:spaceId,kind:text(formData,"kind") as typeof s.instructionKind.enumValues[number],text:text(formData,"text"),validOn:text(formData,"validOn")||null,permanent:!text(formData,"validOn"),childIds,memberIds,createdBy:session.user.id});await trackProductEvent("INSTRUCTION_CREATED",session.user.id,spaceId);revalidatePath("/app");}
export async function addProgramItemAction(formData:FormData){const spaceId=text(formData,"spaceId");const {session,membership}=await requireParentPermission(spaceId,"program");const childIds=formData.getAll("childIds").map(String);const memberIds=formData.getAll("memberIds").map(String);const date=text(formData,"date"),start=text(formData,"start")||null,end=text(formData,"end")||null;await assertChildren(membership.id,childIds);await assertMembers(spaceId,memberIds);await assertMembersCanAccessChildren(spaceId,memberIds,childIds);if(start&&memberIds.length)await assertWithinCareWindow(spaceId,memberIds,date,start,end);const [item]=await db.insert(s.programItems).values({careSpaceId:spaceId,programDate:date,type:text(formData,"type"),title:text(formData,"title"),description:text(formData,"description")||null,location:text(formData,"location")||null,plannedStart:start,plannedEnd:end,createdBy:session.user.id}).returning();if(childIds.length)await db.insert(s.programChildren).values(childIds.map(childId=>({programItemId:item.id,childId})));if(memberIds.length)await db.insert(s.programAssignees).values(memberIds.map(memberId=>({programItemId:item.id,memberId})));revalidatePath("/app");}
export async function updateProgramStatusAction(formData:FormData){const spaceId=text(formData,"spaceId"),itemId=text(formData,"itemId");const {session,membership}=await requirePermission(spaceId,"program");const [item]=await db.select().from(s.programItems).where(and(eq(s.programItems.id,itemId),eq(s.programItems.careSpaceId,spaceId))).limit(1);if(!item)throw new Error("PROGRAM_ITEM_NOT_FOUND");const linkedChildren=(await db.select({id:s.programChildren.childId}).from(s.programChildren).where(eq(s.programChildren.programItemId,itemId))).map(x=>x.id);await assertChildren(membership.id,linkedChildren);const todayIso=await spaceToday(spaceId);if(item.programDate>todayIso)throw new Error("FUTURE_ITEM_CANNOT_BE_REALIZED");if(!isParentRole(membership.role)){const [assigned]=await db.select().from(s.programAssignees).where(and(eq(s.programAssignees.programItemId,itemId),eq(s.programAssignees.memberId,membership.id))).limit(1);if(!assigned)throw new Error("FORBIDDEN");}const status=text(formData,"status") as typeof s.programStatus.enumValues[number];if(!s.programStatus.enumValues.includes(status))throw new Error("INVALID_STATUS");let actualStart:Date|null=null,actualEnd:Date|null=null,completedAt:Date|null=null,completedByMemberId:string|null=null;if(status==="DONE"){if(item.programDate===todayIso){actualStart=new Date();actualEnd=actualStart;}else{const startText=item.plannedStart||"00:00",endText=item.plannedEnd||startText;actualStart=localDateTime(item.programDate,startText)||new Date();actualEnd=localDateTime(item.programDate,endText)||actualStart;}completedAt=new Date();completedByMemberId=membership.id;}await db.update(s.programItems).set({status,note:text(formData,"note")||null,actualStart,actualEnd,completedAt,completedByMemberId}).where(and(eq(s.programItems.id,itemId),eq(s.programItems.careSpaceId,spaceId)));await db.insert(s.activityLogs).values({careSpaceId:spaceId,actorUserId:session.user.id,action:"PROGRAM_STATUS_CHANGED",entityType:"program_item",entityId:itemId,metadata:{status,completedByMemberId}});await trackProductEvent("ACTIVITY_STATUS_CHANGED",session.user.id,spaceId,{status});if(status==="DONE"&&item.status!=="DONE")await notifySpaceUsers({spaceId,excludeUserId:session.user.id,kind:"activities",type:"ACTIVITY_DONE",title:`${item.title} terminé`,body:item.description||undefined,url:`/app?space=${spaceId}&section=journal`,childIds:linkedChildren});revalidatePath("/app");}
export async function addTaskAction(formData:FormData){const spaceId=text(formData,"spaceId");const {session,membership}=await requireParentPermission(spaceId,"tasks");const assignees=formData.getAll("memberIds").map(String);const childIds=formData.getAll("childIds").map(String);const date=text(formData,"date")||null,time=text(formData,"time")||null;await assertChildren(membership.id,childIds);await assertMembers(spaceId,assignees);await assertMembersCanAccessChildren(spaceId,assignees,childIds);if(date&&time&&assignees.length)await assertWithinCareWindow(spaceId,assignees,date,time,time);const [task]=await db.insert(s.tasks).values({careSpaceId:spaceId,taskDate:date,time,title:text(formData,"title"),description:text(formData,"description")||null,createdBy:session.user.id}).returning();if(assignees.length)await db.insert(s.taskAssignees).values(assignees.map(memberId=>({taskId:task.id,memberId})));if(childIds.length)await db.insert(s.taskChildren).values(childIds.map(childId=>({taskId:task.id,childId})));revalidatePath("/app");}
export async function updateTaskStatusAction(formData:FormData){const spaceId=text(formData,"spaceId"),taskId=text(formData,"taskId");const {membership}=await requirePermission(spaceId,"tasks");const [task]=await db.select().from(s.tasks).where(and(eq(s.tasks.id,taskId),eq(s.tasks.careSpaceId,spaceId))).limit(1);if(!task)throw new Error("TASK_NOT_FOUND");const linkedChildren=(await db.select({id:s.taskChildren.childId}).from(s.taskChildren).where(eq(s.taskChildren.taskId,taskId))).map(x=>x.id);await assertChildren(membership.id,linkedChildren);if(task.taskDate&&task.taskDate>await spaceToday(spaceId))throw new Error("FUTURE_TASK_CANNOT_BE_REALIZED");if(!isParentRole(membership.role)){const [assigned]=await db.select().from(s.taskAssignees).where(and(eq(s.taskAssignees.taskId,taskId),eq(s.taskAssignees.memberId,membership.id))).limit(1);if(!assigned)throw new Error("FORBIDDEN");}const status=text(formData,"status") as typeof s.taskStatus.enumValues[number];if(!s.taskStatus.enumValues.includes(status))throw new Error("INVALID_STATUS");await db.update(s.tasks).set({status,note:text(formData,"note")||null}).where(and(eq(s.tasks.id,taskId),eq(s.tasks.careSpaceId,spaceId)));revalidatePath("/app");}
export async function addRoutineAction(formData:FormData){const spaceId=text(formData,"spaceId");const {session}=await requireParentPermission(spaceId,"tasks");const [routine]=await db.insert(s.routines).values({careSpaceId:spaceId,name:text(formData,"name"),description:text(formData,"description")||null,createdBy:session.user.id}).returning();const lines=text(formData,"items").split("\n").map(x=>x.trim()).filter(Boolean);if(lines.length)await db.insert(s.routineItems).values(lines.map((title,position)=>({routineId:routine.id,title,position})));await trackProductEvent("ROUTINE_CREATED",session.user.id,spaceId);revalidatePath("/app");}
export async function applyRoutineAction(formData:FormData){const spaceId=text(formData,"spaceId");const {session,membership}=await requireParentPermission(spaceId,"tasks");const routineId=text(formData,"routineId"),memberId=text(formData,"memberId"),childId=text(formData,"childId"),taskDate=text(formData,"date");await assertMembers(spaceId,[memberId]);if(childId)await assertChildren(membership.id,[childId]);if(childId)await assertMembersCanAccessChildren(spaceId,[memberId],[childId]);const [routine]=await db.select().from(s.routines).where(and(eq(s.routines.id,routineId),eq(s.routines.careSpaceId,spaceId))).limit(1);if(!routine)throw new Error("INVALID_ROUTINE");const items=await db.select().from(s.routineItems).where(eq(s.routineItems.routineId,routineId));for(const item of items){const [task]=await db.insert(s.tasks).values({careSpaceId:spaceId,taskDate,title:item.title,description:item.description,createdBy:session.user.id}).returning();await db.insert(s.taskAssignees).values({taskId:task.id,memberId});if(childId)await db.insert(s.taskChildren).values({taskId:task.id,childId});}revalidatePath("/app");}
