import Link from "next/link";
import { redirect } from "next/navigation";
import { createSpaceAction } from "@/app/actions/space";
import { requireUser } from "@/lib/security";
import { spacesForUser } from "@/lib/data";
import { serverConfigured } from "@/lib/env";
import { Icon } from "@/components/ui/icons";

export const dynamic="force-dynamic";
export default async function OnboardingPage({searchParams}:{searchParams:Promise<{mode?:string}>}){
  if(!serverConfigured())redirect("/");const session=await requireUser();const spaces=await spacesForUser(session.user.id);if(spaces.length)redirect(`/app?space=${spaces[0].space.id}`);const {mode}=await searchParams;
  if(mode!=="parent"&&mode!=="caregiver")return <main className="v4-onboarding"><section className="v4-onboarding-card v5-onboarding-choice"><span className="v4-logo">Y</span><span className="v4-eyebrow">Bienvenue {session.user.name?.split(" ")[0]||""}</span><h1>Comment allez-vous utiliser Youpiii ?</h1><p className="v4-onboarding-lead">Choisissez simplement votre situation. Vous pourrez participer à plusieurs familles avec le même compte.</p><div className="v5-role-choice"><Link href="/onboarding?mode=parent"><span className="v4-row-icon"><Icon name="child"/></span><span><strong>Je suis parent</strong><small>Créer ma famille et inviter les personnes qui gardent mes enfants.</small></span><Icon name="chevronRight"/></Link><Link href="/onboarding?mode=caregiver"><span className="v4-row-icon"><Icon name="people"/></span><span><strong>Je garde des enfants</strong><small>Rejoindre une ou plusieurs familles avec leurs invitations.</small></span><Icon name="chevronRight"/></Link></div></section></main>;
  if(mode==="caregiver")return <main className="v4-onboarding"><section className="v4-onboarding-card"><span className="v4-logo">Y</span><span className="v4-eyebrow">Intervenant</span><h1>Un seul compte pour toutes vos familles.</h1><p className="v4-onboarding-lead">Demandez au parent de vous envoyer l’invitation Youpiii par e-mail, WhatsApp, SMS ou QR code. Dès que vous l’acceptez, la famille rejoint automatiquement votre agenda.</p><div className="v5-invite-summary"><span>Votre compte</span><strong>{session.user.email}</strong></div><div className="v5-onboarding-tips"><div><b>1</b><span><strong>Ouvrez le lien</strong><small>Le lien doit être destiné à cette adresse e-mail.</small></span></div><div><b>2</b><span><strong>Acceptez la famille</strong><small>Les enfants et droits autorisés sont ajoutés automatiquement.</small></span></div><div><b>3</b><span><strong>Utilisez “Aujourd’hui”</strong><small>Si vous avez plusieurs familles, elles apparaissent dans un seul agenda.</small></span></div></div><Link href="/onboarding" className="btn soft full">Changer de choix</Link></section></main>;
  return <main className="v4-onboarding"><section className="v4-onboarding-card"><span className="v4-logo">Y</span><span className="v4-eyebrow">Parent · Bienvenue {session.user.name?.split(" ")[0]||""}</span><h1>Votre famille, en une minute.</h1><p className="v4-onboarding-lead">Créez l’espace et votre premier enfant. Ensuite, invitez la nounou puis ajoutez ses horaires dans Planning.</p><div className="v4-onboarding-steps"><span className="is-active"><b>1</b>Famille</span><span><b>2</b>Enfant</span><span><b>3</b>Inviter</span><span><b>✓</b>Terminé</span></div><form className="v4-form" action={createSpaceAction}><div className="v4-field"><label>Nom de votre espace</label><input name="spaceName" placeholder="Famille Martin" required autoFocus/></div><div className="v4-field"><label>Prénom du premier enfant</label><input name="childName" placeholder="Emma" required/></div><div className="v4-field"><label>Date de naissance <span className="muted">· facultatif</span></label><input type="date" name="birthDate"/></div><button className="btn brandbtn full">Créer mon espace <Icon name="chevronRight" size={17}/></button></form><p className="v4-form-help">Vous pourrez compléter l’école, les allergies, les habitudes et les contacts d’urgence ensuite.</p><Link href="/onboarding" className="v4-text-action">Je ne suis pas parent</Link></section></main>;
}
