import Link from "next/link";
import { redirect } from "next/navigation";
import { missingServerEnv, serverConfigured } from "@/lib/env";
import { Icon } from "@/components/ui/icons";

export const dynamic="force-dynamic";
export default async function Home(){
  if(!serverConfigured()){const missing=missingServerEnv();return <main className="v4-main setup"><section className="v4-card"><span className="v4-logo">Y</span><h1>Nanny Youpiii</h1><p className="muted">Le frontend est prêt. La configuration serveur suivante est nécessaire.</p><div className="v4-divider"/>{missing.map(key=><div className="v4-list-row" key={key}><code>{key}</code><span className="v4-badge v4-badge-danger">Requis</span></div>)}</section></main>}
  const {auth}=await import("@/lib/auth");const {data}=await auth.getSession();if(data?.user)redirect("/app");
  return <main className="v57-marketing">
    <header className="v57-marketing-header"><div className="v57-marketing-header-inner"><Link href="/" className="v57-brand"><span className="v57-brand-mark">Y</span><span className="v57-brand-copy"><strong>Nanny Youpiii</strong><small>Le cerveau partagé de la garde</small></span></Link><nav className="v57-marketing-nav" aria-label="Navigation du site"><a href="#fonctionnement">Comment ça marche</a><a href="#pourquoi">Pourquoi Youpiii</a><a href="#confidentialite">Confidentialité</a><Link href="/demo?role=parent&section=today">Démo</Link></nav><div className="v57-header-actions"><Link className="btn soft" href="/auth/sign-in">Se connecter</Link><Link className="btn brandbtn v57-signup" href="/auth/sign-up">Créer mon espace</Link></div></div></header>

    <section className="v57-hero"><div className="v57-hero-copy"><span className="v57-kicker"><Icon name="heart" size={15}/> Parents · nounous · baby-sitters</span><h1>Le cerveau partagé de votre <em>garde d’enfants.</em></h1><p className="v57-hero-lead">Tout le monde sait ce qui est prévu, ce qu’il faut faire et ce qui s’est réellement passé. Planning, consignes, activités, courses et informations utiles restent réunis dans un seul espace privé.</p><div className="v57-hero-actions"><Link className="btn brandbtn" href="/auth/sign-up">Créer mon espace <Icon name="chevronRight" size={17}/></Link><Link className="btn soft" href="/demo?role=parent&section=today"><Icon name="eye" size={17}/> Explorer la démo</Link></div><div className="v57-trust-row"><span><Icon name="check" size={14}/> Données privées</span><span><Icon name="check" size={14}/> Aucune revente</span><span><Icon name="check" size={14}/> Pas de publicité ciblée</span><span><Icon name="check" size={14}/> Démo sans inscription</span></div></div>
      <div className="v57-product-frame" aria-label="Aperçu de Nanny Youpiii"><div className="v57-product-glow"/><div className="v57-product-phone"><div className="v57-product-screen"><div className="v57-product-top"><span><small>FAMILLE MARTIN</small><strong>Aujourd’hui</strong></span><span className="v57-product-bell"><Icon name="bell" size={17}/></span></div><div className="v57-product-greeting"><small>Mardi 11 août</small><h3>Bonjour Camille</h3><p>La journée de Lina et Jules, au même endroit.</p></div><div className="v57-product-next"><span><Icon name="park" size={18}/></span><span><small>PROCHAIN</small><strong>15:00 · Parc avec Nora</strong></span><Icon name="chevronRight" size={16}/></div><div className="v57-product-day"><div className="v57-product-day-head"><strong>Aujourd’hui</strong><small>5 repères</small></div><div className="v57-product-line"><time>14:00</time><span><Icon name="school" size={15}/></span><strong>Sortie d’école</strong><b>Fait</b></div><div className="v57-product-line"><time>14:30</time><span><Icon name="meal" size={15}/></span><strong>Goûter</strong><span/></div><div className="v57-product-line"><time>15:00</time><span><Icon name="park" size={15}/></span><strong>Parc</strong><span/></div><div className="v57-product-line"><time>17:15</time><span><Icon name="bath" size={15}/></span><strong>Bain</strong><span/></div><div className="v57-product-note"><Icon name="alert" size={16}/><span>Bonnet de piscine dans le sac bleu.</span></div></div></div></div><div className="v57-product-private"><Icon name="check" size={18}/><span><strong>Espace privé</strong><small>Uniquement les adultes invités</small></span></div></div>
    </section>

    <section className="v57-social-proof" aria-label="Principes du produit"><div className="v57-social-proof-inner"><div className="v57-social-proof-intro"><strong>Moins de messages. Moins d’oublis.</strong><small>Une seule source de vérité pour la garde.</small></div><div><strong>Multi-enfants</strong><small>Un planning différent pour chaque enfant si nécessaire.</small></div><div><strong>Multi-intervenants</strong><small>Nounou de journée, baby-sitter, autre parent ou co-garde.</small></div><div><strong>Multi-familles</strong><small>Une nounou retrouve ses familles avec le même compte.</small></div></div></section>

    <section className="v57-section" id="pourquoi"><div className="v57-section-head center"><span className="v4-eyebrow">Pourquoi Youpiii</span><h2>Parce que la garde ne devrait pas vivre entre WhatsApp, un calendrier et des post-it.</h2><p>Les informations importantes changent toute la journée. Youpiii les remet au bon endroit sans obliger la nounou à apprendre une méthode compliquée.</p></div><div className="v57-feature-grid"><article className="v57-feature-card is-coral"><span className="v57-feature-icon"><Icon name="sun"/></span><h3>Aujourd’hui : savoir quoi faire maintenant</h3><p>Horaires de garde, prochain repère, activités et consignes importantes sont visibles en quelques secondes. La nounou n’a pas besoin de chercher l’information.</p></article><article className="v57-feature-card"><span className="v57-feature-icon"><Icon name="calendar"/></span><h3>Planning : toute l’organisation au même endroit</h3><p>Activités, horaires réguliers, exceptions et routines vivent dans un seul calendrier. Une modification peut prévenir directement l’intervenant concerné.</p></article><article className="v57-feature-card"><span className="v57-feature-icon"><Icon name="shopping"/></span><h3>Courses : acheter sans mélanger les comptes</h3><p>Une liste commune, le prix réellement payé, la caisse disponible et les avances à rembourser restent simples à suivre.</p></article><article className="v57-feature-card is-dark"><span className="v57-feature-icon"><Icon name="people"/></span><h3>Équipe & accès : chacun voit seulement ce qui le concerne</h3><p>Parents, nounous et baby-sitters peuvent avoir des enfants et des accès différents. Le même compte peut servir dans plusieurs familles.</p></article></div></section>

    <section className="v57-section" id="fonctionnement"><div className="v57-section-head"><span className="v4-eyebrow">Une logique naturelle</span><h2>Avant. Pendant. Après. C’est tout.</h2><p>Youpiii suit le déroulé réel d’une garde au lieu de demander aux utilisateurs de réfléchir à la structure de l’application.</p></div><div className="v57-flow"><article><span className="v57-flow-number">1</span><h3>Avant · le parent prépare</h3><p>Il pose les horaires, les activités prévues, une routine si besoin et les consignes importantes. La nounou reçoit les changements utiles.</p></article><article><span className="v57-flow-number">2</span><h3>Pendant · la nounou vit la journée</h3><p>Elle ouvre Aujourd’hui, voit immédiatement ce qui compte et ajoute seulement les moments réellement utiles. Le début de garde reste facultatif.</p></article><article><span className="v57-flow-number">3</span><h3>Après · tout est déjà là</h3><p>Les parents retrouvent ce qui a été fait et les éventuels retours de fin de garde. Pas besoin de reconstruire la journée dans une conversation.</p></article></div></section>

    <section className="v57-privacy" id="confidentialite"><div className="v57-privacy-inner"><div className="v57-privacy-copy"><span className="v4-eyebrow" style={{color:"rgba(255,255,255,.58)"}}>Vie privée par défaut</span><h2>Vos données servent à votre famille. Pas à créer un business autour de votre vie privée.</h2><p>Nanny Youpiii est un outil d’organisation privé. Les informations saisies servent au fonctionnement de l’application, à la sécurité des accès et aux notifications que vous choisissez.</p><Link href="/privacy" className="v57-privacy-link">Lire notre politique de confidentialité</Link></div><div className="v57-privacy-list"><div className="v57-privacy-item"><span><Icon name="check" size={17}/></span><span><strong>Nous ne vendons pas vos données</strong><small>Aucune commercialisation des informations familiales ou des données concernant les enfants.</small></span></div><div className="v57-privacy-item"><span><Icon name="ban" size={17}/></span><span><strong>Pas de publicité ciblée à partir des enfants</strong><small>Les informations d’un enfant ne servent pas à construire un profil publicitaire.</small></span></div><div className="v57-privacy-item"><span><Icon name="people" size={17}/></span><span><strong>Accès réservé aux personnes invitées</strong><small>Chaque famille décide quels adultes et quels enfants sont accessibles dans son espace.</small></span></div><div className="v57-privacy-item"><span><Icon name="settings" size={17}/></span><span><strong>Vous gardez la main</strong><small>Réglages, export et suppression du compte sont accessibles depuis l’application.</small></span></div></div></div></section>

    <section className="v57-section"><div className="v57-section-head center"><span className="v4-eyebrow">Deux côtés, une seule application</span><h2>Utile au parent. Évidente pour la nounou.</h2><p>Une application familiale n’est adoptée que si la personne qui garde les enfants a elle aussi intérêt à l’ouvrir.</p></div><div className="v57-personas"><article className="v57-persona"><div className="v57-persona-top"><span className="v57-persona-icon"><Icon name="child"/></span><h3>Côté parent</h3></div><ul><li><Icon name="check" size={15}/>Préparer la semaine et les exceptions</li><li><Icon name="check" size={15}/>Partager les consignes importantes une seule fois</li><li><Icon name="check" size={15}/>Savoir ce qui s’est passé sans envoyer dix messages</li><li><Icon name="check" size={15}/>Gérer plusieurs enfants et plusieurs intervenants</li></ul></article><article className="v57-persona"><div className="v57-persona-top"><span className="v57-persona-icon"><Icon name="people"/></span><h3>Côté nounou</h3></div><ul><li><Icon name="check" size={15}/>Voir sa journée immédiatement</li><li><Icon name="check" size={15}/>Être prévenue lorsqu’un planning la concernant change</li><li><Icon name="check" size={15}/>Ajouter un moment après coup avec son heure réelle</li><li><Icon name="check" size={15}/>Retrouver plusieurs familles avec le même compte</li></ul></article></div></section>

    <section className="v57-final-cta"><div><span className="v4-eyebrow" style={{color:"rgba(255,255,255,.7)"}}>Essayez avant de créer un compte</span><h2>La démo montre exactement le produit.</h2><p>Passez du rôle parent au rôle nounou et explorez Aujourd’hui, Planning, Courses et Plus.</p></div><div className="v57-hero-actions"><Link className="btn primary" href="/demo?role=parent&section=today"><Icon name="eye" size={17}/> Ouvrir la démo</Link><Link className="btn soft" href="/auth/sign-up">Créer mon espace</Link></div></section>

    <footer className="v57-footer"><Link href="/" className="v57-brand"><span className="v57-brand-mark">Y</span><span className="v57-brand-copy"><strong>Nanny Youpiii</strong><small>Le cerveau partagé de la garde</small></span></Link><div className="v57-footer-links"><Link href="/demo?role=parent&section=today">Démo</Link><Link href="/privacy">Confidentialité</Link><Link href="/terms">Conditions</Link><Link href="/auth/sign-in">Connexion</Link></div></footer>
  </main>;
}
