import Link from "next/link";
import { redirect } from "next/navigation";
import { missingServerEnv, serverConfigured } from "@/lib/env";

export const dynamic = "force-dynamic";

export default async function Home() {
  if (!serverConfigured()) {
    const missing = missingServerEnv();
    return <main className="main setup"><div className="card"><div className="logo">Y!</div><h1>Nanny Youpiii V3</h1><p className="muted">Le code V3 est déployé, mais le backend multi-utilisateurs attend ses ressources de production.</p><div className="divider"/><div className="sectiontitle">Configuration manquante</div><div className="list">{missing.map(k=><div className="item" key={k}><code>{k}</code><span className="pill red">requis</span></div>)}</div></div></main>;
  }
  const { auth } = await import("@/lib/auth");
  const { data } = await auth.getSession();
  if (data?.user) redirect("/app");

  return <main className="landing"><header className="landing-head"><div className="brand"><div className="logo">Y!</div><span>Nanny Youpiii</span></div><div className="row"><Link className="btn soft" href="/auth/sign-in">Se connecter</Link><Link className="btn primary hide-mobile" href="/auth/sign-up">Créer mon espace</Link></div></header>
    <section className="landing-hero"><div className="landing-copy"><span className="landing-kicker">Organisation quotidienne de la garde</span><h1>Tout ce qui concerne vos enfants, partagé au bon moment avec les bonnes personnes.</h1><p>Planning, tâches, consignes, courses, caisse et transmissions dans une seule application simple, pensée pour les parents, nounous et baby-sitters.</p><div className="row wrap landing-actions"><Link className="btn brandbtn" href="/auth/sign-up">Créer mon espace</Link><Link className="btn soft" href="/demo?role=parent&section=today">Voir la démo Parent</Link><Link className="btn soft" href="/demo?role=nanny&section=today">Voir la démo Nounou</Link></div><div className="landing-proof"><span>✓ Multi-enfants</span><span>✓ Multi-nounous</span><span>✓ Mobile-first</span><span>✓ Permissions par enfant</span></div></div><div className="landing-phone"><div className="demo-mini-head"><span className="pill green">Aujourd’hui</span><b>Famille Démo</b></div><div className="demo-mini-title">Bonjour 👋</div><div className="demo-mini-card"><b>15:30 · Piscine</b><span>Lina · Nora</span></div><div className="demo-mini-card"><b>🛒 3 produits à acheter</b><span>Caisse disponible · 85,30 €</span></div><div className="demo-mini-card"><b>⚠️ Important aujourd’hui</b><span>Penser au bonnet pour la piscine</span></div></div></section>

    <section className="landing-section"><div className="eyebrow">Une application, un fil conducteur</div><h2>Prévoir → organiser → acheter → transmettre</h2><div className="feature-grid"><article className="feature-card"><div className="feature-icon">☀️</div><h3>Aujourd’hui</h3><p>Chacun voit uniquement ce qu’il doit savoir pour la journée : horaires, programme, tâches et consignes importantes.</p></article><article className="feature-card"><div className="feature-icon">📅</div><h3>Planning partagé</h3><p>Consultez le passé et préparez les jours à venir pour un ou plusieurs enfants et intervenants.</p></article><article className="feature-card"><div className="feature-icon">🛒</div><h3>Courses & caisse</h3><p>Un achat est saisi une seule fois : produit acheté, prix payé, caisse mise à jour et avance éventuelle calculée automatiquement.</p></article><article className="feature-card"><div className="feature-icon">💬</div><h3>Transmission</h3><p>Les parents comprennent rapidement la journée et une nounou peut transmettre les informations utiles à la personne suivante.</p></article></div></section>

    <section className="landing-section landing-split"><div><div className="eyebrow">Des vues vraiment différentes</div><h2>Le parent organise. La nounou va à l’essentiel.</h2><p className="muted">Les parents gèrent les enfants, l’équipe, les accès et le planning. Une nounou ne voit que les enfants, horaires, tâches, consignes, courses et caisse auxquels elle est autorisée.</p></div><div className="card"><div className="item"><div><strong>Parent</strong><small>Configuration · équipe · permissions · vue d’ensemble</small></div><span className="pill">Administrer</span></div><div className="item" style={{marginTop:8}}><div><strong>Nounou / baby-sitter</strong><small>Aujourd’hui · planning · courses & caisse</small></div><span className="pill green">Simple</span></div></div></section>

    <section className="landing-cta"><div><div className="eyebrow">Tester avant de s’inscrire</div><h2>Explorez une famille de démonstration.</h2><p>Comparez la vue Parent et la vue Nounou avec des données déjà remplies, sans créer de compte.</p></div><div className="row wrap"><Link className="btn primary" href="/demo?role=parent&section=today">Démo Parent</Link><Link className="btn soft" href="/demo?role=nanny&section=today">Démo Nounou</Link></div></section>
    <footer className="landing-foot"><div className="brand"><div className="logo">Y!</div><span>Nanny Youpiii</span></div><span>Organiser simplement le quotidien des enfants entre les adultes qui s’en occupent.</span></footer>
  </main>;
}
