"use client";
import { FormEvent, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { authClient } from "@/lib/auth-client";

export function SignInForm() {
  const [error,setError]=useState(""); const [loading,setLoading]=useState(false); const router=useRouter(); const params=useSearchParams();
  async function submit(e:FormEvent<HTMLFormElement>){ e.preventDefault(); setLoading(true); setError(""); const f=new FormData(e.currentTarget); const {error}=await authClient.signIn.email({email:String(f.get("email")),password:String(f.get("password")),rememberMe:true}); setLoading(false); if(error){setError(error.message||"Connexion impossible");return;} router.push(params.get("next")||"/app"); router.refresh(); }
  return <form className="form" onSubmit={submit}><div className="field"><label>E-mail</label><input name="email" type="email" required autoComplete="email"/></div><div className="field"><label>Mot de passe</label><input name="password" type="password" required autoComplete="current-password"/></div>{error&&<div className="error">{error}</div>}<button className="btn brandbtn full" disabled={loading}>{loading?"Connexion…":"Se connecter"}</button></form>;
}

export function SignUpForm() {
  const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(false); const params=useSearchParams();
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const f=new FormData(e.currentTarget);const password=String(f.get("password"));if(password!==String(f.get("confirm"))){setError("Les mots de passe ne correspondent pas");setLoading(false);return;}const firstName=String(f.get("firstName"));const lastName=String(f.get("lastName"));const name=`${firstName} ${lastName}`.trim();const callbackURL=params.get("next")||"/onboarding";const {error}=await authClient.signUp.email({email:String(f.get("email")),password,name,firstName,lastName,callbackURL});setLoading(false);if(error){setError(error.message||"Inscription impossible");return;}setMessage("Compte créé. Vérifiez votre e-mail pour continuer.");}
  return <form className="form" onSubmit={submit}><div className="row"><div className="field" style={{flex:1}}><label>Prénom</label><input name="firstName" required/></div><div className="field" style={{flex:1}}><label>Nom</label><input name="lastName" required/></div></div><div className="field"><label>E-mail</label><input name="email" type="email" required/></div><div className="field"><label>Mot de passe</label><input name="password" type="password" minLength={10} required/></div><div className="field"><label>Confirmer</label><input name="confirm" type="password" minLength={10} required/></div>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}<button className="btn brandbtn full" disabled={loading}>{loading?"Création…":"Créer mon compte"}</button></form>;
}

export function ForgotPasswordForm(){const [message,setMessage]=useState("");const [error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await authClient.requestPasswordReset({email:String(f.get("email")),redirectTo:`${location.origin}/reset-password`});if(error)setError(error.message||"Impossible d’envoyer le lien");else setMessage("Si cette adresse existe, un e-mail de réinitialisation vient d’être envoyé.");}return <form className="form" onSubmit={submit}><div className="field"><label>E-mail</label><input name="email" type="email" required/></div>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}<button className="btn brandbtn full">Envoyer le lien</button></form>}

export function ResetPasswordForm(){const params=useSearchParams();const [message,setMessage]=useState("");const [error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const token=params.get("token");if(!token){setError("Lien invalide ou expiré");return;}const f=new FormData(e.currentTarget);const p=String(f.get("password"));if(p!==String(f.get("confirm"))){setError("Les mots de passe ne correspondent pas");return;}const {error}=await authClient.resetPassword({newPassword:p,token});if(error)setError(error.message||"Réinitialisation impossible");else setMessage("Mot de passe modifié. Vous pouvez vous connecter.");}return <form className="form" onSubmit={submit}><div className="field"><label>Nouveau mot de passe</label><input name="password" type="password" minLength={10} required/></div><div className="field"><label>Confirmer</label><input name="confirm" type="password" minLength={10} required/></div>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}<button className="btn brandbtn full">Définir le nouveau mot de passe</button></form>}

export function SignOutButton(){const router=useRouter();return <button className="btn soft" onClick={async()=>{await authClient.signOut();router.push("/");router.refresh();}}>Déconnexion</button>}
