import Link from "next/link";
import { and, asc, eq } from "drizzle-orm";
import type { children as childrenTable, members as membersTable, programItems as programItemsTable } from "@/db/schema";
import { db } from "@/db";
import * as s from "@/db/schema";
import { addActivityAction, deleteActivityAction, saveActivityLibraryAction, updateActivityAction } from "@/app/actions/activity";
import { ACTIVITY_LIBRARY_ROUTINE_NAME, DEFAULT_ACTIVITY_PRESETS, MAX_ACTIVITY_PRESETS } from "@/lib/activity";
import { Icon } from "@/components/ui/icons";

type Child=typeof childrenTable.$inferSelect;
type Member=typeof membersTable.$inferSelect;
type ProgramItem=typeof programItemsTable.$inferSelect;

async function activityPresets(spaceId:string){
  const [library]=await db.select({id:s.routines.id}).from(s.routines).where(and(eq(s.routines.careSpaceId,spaceId),eq(s.routines.name,ACTIVITY_LIBRARY_ROUTINE_NAME))).limit(1);
  if(!library)return [...DEFAULT_ACTIVITY_PRESETS];
  const items=await db.select({title:s.routineItems.title}).from(s.routineItems).where(eq(s.routineItems.routineId,library.id)).orderBy(asc(s.routineItems.position));
  const names=items.map(item=>item.title.trim()).filter(Boolean).slice(0,MAX_ACTIVITY_PRESETS);
  return names.length?names:[...DEFAULT_ACTIVITY_PRESETS];
}

export async function ActivitySheet({spaceId,selectedDate,children,caregivers,memberName,parent,closeHref,item,childIds=[],memberIds=[]}:{spaceId:string;selectedDate:string;children:Child[];caregivers:Member[];memberName:(member:Member)=>string;parent:boolean;closeHref:string;item?:ProgramItem;childIds?:string[];memberIds?:string[]}){
  const presets=await activityPresets(spaceId);const editing=Boolean(item),done=item?.status==="DONE",scheduled=editing||parent,action=editing?updateActivityAction:addActivityAction;
  const currentPreset=item?.title?presets.find(name=>name.toLocaleLowerCase("fr-FR")===item.title.toLocaleLowerCase("fr-FR")):undefined;
  const initialChoice=currentPreset?`PRESET::${currentPreset}`:item?.title?`CURRENT::${item.title}`:`PRESET::${presets[0]}`;
  const slots=[...presets,...Array.from({length:Math.max(0,MAX_ACTIVITY_PRESETS-presets.length)},()=>"")].slice(0,MAX_ACTIVITY_PRESETS);
  return <div className="v4-compose-sheet"><Link className="v4-sheet-backdrop" href={closeHref} aria-label="Fermer"/><section className="v4-bottom-sheet v4-activity-sheet v51-activity-sheet" role="dialog" aria-modal="true"><div className="v4-sheet-handle"/><div className="v4-sheet-heading"><div><span className="v4-eyebrow">Activité</span><h2>{editing?"Modifier":"Ajouter"}</h2><p className="v4-form-help">{parent?"Préparez seulement les repères utiles de la journée.":"Ajoutez seulement ce qui mérite d’être transmis aux parents."}</p></div><Link href={closeHref} className="v4-icon-button" aria-label="Fermer"><Icon name="close"/></Link></div>
    <form className="v4-form" action={action}><input type="hidden" name="spaceId" value={spaceId}/><input type="hidden" name="returnTo" value={closeHref}/>{item&&<input type="hidden" name="itemId" value={item.id}/>}<fieldset className="v4-activity-fieldset v51-activity-picker"><div className="v51-picker-heading"><legend>Activité</legend>{parent&&<span>{presets.length}/{MAX_ACTIVITY_PRESETS} régulières</span>}</div><label className="v51-select-wrap"><span className="v51-select-icon"><Icon name="activity" size={19}/></span><select name="activityType" defaultValue={initialChoice} aria-label="Choisir une activité"><optgroup label="Activités de la famille">{presets.map(name=><option value={`PRESET::${name}`} key={name}>{name}</option>)}</optgroup>{item?.title&&!currentPreset&&<optgroup label="Activité actuelle"><option value={`CURRENT::${item.title}`}>{item.title}</option></optgroup>}<option value="OTHER">Autre…</option></select><span className="v51-select-chevron"><Icon name="chevronRight" size={17}/></span></label><div className="v51-new-activity"><label htmlFor="custom-activity-name">Seulement si vous choisissez “Autre”</label><input id="custom-activity-name" name="customTitle" maxLength={80} placeholder="Ex. Escalade, rendez-vous, pique-nique…"/><small>Une activité ponctuelle reste ponctuelle : elle ne sera jamais ajoutée automatiquement à la liste.</small></div></fieldset>
      {done?<div className="v5-history-lock"><Icon name="check"/><span><strong>Activité déjà réalisée</strong><small>Vous pouvez corriger le contenu ou l’attribution. L’historique de réalisation reste conservé.</small></span><input type="hidden" name="timing" value="SCHEDULED"/><input type="hidden" name="date" value={item?.programDate||selectedDate}/><input type="hidden" name="time" value={item?.plannedStart||""}/><input type="hidden" name="end" value={item?.plannedEnd||""}/></div>:<fieldset className="v4-activity-fieldset"><legend>Quand ?</legend><div className="v4-activity-timing"><label><input type="radio" name="timing" value="NOW" defaultChecked={!scheduled}/><span>Maintenant</span></label><label><input type="radio" name="timing" value="SCHEDULED" defaultChecked={scheduled}/><span>Choisir</span></label></div><div className="v4-activity-scheduled"><div className="v4-form-row"><div className="v4-field"><label>Date</label><input name="date" type="date" defaultValue={item?.programDate||selectedDate}/></div><div className="v4-field"><label>Heure</label><input name="time" type="time" defaultValue={item?.plannedStart||""}/></div></div></div></fieldset>}
      {children.length>0&&<fieldset className="v4-activity-fieldset"><legend>Pour qui ?</legend><div className="v4-activity-people">{children.map(child=><label key={child.id}><input type="checkbox" name="childIds" value={child.id} defaultChecked={childIds.includes(child.id)||(!editing&&children.length===1)}/><span>{child.firstName}</span></label>)}</div></fieldset>}
      <div className="v4-field"><label>Détails <small>(facultatif)</small></label><textarea name="description" rows={4} defaultValue={item?.description||""} placeholder={'Ex. pour un repas :\nBrocolis\nPoulet\nYaourt'}/></div>
      {parent&&caregivers.length>0&&<details className="v4-more-options"><summary>Plus d’options</summary><div className="v4-form"><div className="v4-field"><label>Qui s’en occupe ?</label><div className="v4-activity-people">{caregivers.map(member=><label key={member.id}><input type="checkbox" name="memberIds" value={member.id} defaultChecked={memberIds.includes(member.id)||(!editing&&caregivers.length===1)}/><span>{memberName(member)}</span></label>)}</div></div>{!done&&<div className="v4-field"><label>Heure de fin</label><input name="end" type="time" defaultValue={item?.plannedEnd||""}/></div>}</div></details>}
      <button className="btn brandbtn full">{editing?"Enregistrer":parent?"Ajouter au planning":"Ajouter comme fait"}</button></form>
    {parent&&<details className="v51-library-settings"><summary><span><Icon name="settings" size={18}/><span><strong>Personnaliser les activités</strong><small>Choisissez les quelques rubriques que votre famille utilise vraiment.</small></span></span><Icon name="chevronRight" size={17}/></summary><form action={saveActivityLibraryAction} className="v51-library-form"><input type="hidden" name="spaceId" value={spaceId}/><div className="v51-library-note"><strong>Jusqu’à {MAX_ACTIVITY_PRESETS} activités régulières</strong><small>Renommez directement une ligne. Laissez-la vide pour la retirer. “Autre” reste toujours disponible pour l’exceptionnel.</small></div><div className="v51-library-list">{slots.map((name,index)=><label className="v51-library-row" key={index}><span>{index+1}</span><input name="names" defaultValue={name} maxLength={60} placeholder={index<4?`Activité ${index+1}`:"Facultatif"}/></label>)}</div><button className="btn primary full" type="submit">Enregistrer ma liste</button></form></details>}
    {item&&<form action={deleteActivityAction} className="v4-activity-delete"><input type="hidden" name="spaceId" value={spaceId}/><input type="hidden" name="itemId" value={item.id}/><input type="hidden" name="returnTo" value={closeHref}/><button className="btn soft full" type="submit">Supprimer cette activité</button></form>}
  </section></div>;
}
