import Link from "next/link";
import { addChildAction } from "@/app/actions/space";
import { updateChildAction } from "@/app/actions/management";
import { Icon } from "@/components/ui/icons";
import { Avatar, Card, EmptyState, PageTitle, StatusBadge } from "@/components/ui/primitives";
import type { children as childrenTable } from "@/db/schema";

type Child=typeof childrenTable.$inferSelect;type Query=(extra:Record<string,string>)=>string;
function ageLabel(birthDate:string|null){if(!birthDate)return "Âge non renseigné";const birth=new Date(`${birthDate}T12:00:00`);const now=new Date();let years=now.getFullYear()-birth.getFullYear();if(now.getMonth()<birth.getMonth()||(now.getMonth()===birth.getMonth()&&now.getDate()<birth.getDate()))years--;return years>=0?`${years} an${years>1?"s":""}`:"Âge non renseigné";}
function AddChildSheet({spaceId,q}:{spaceId:string;q:Query}){const close=q({section:"more",area:"children",compose:""});return <div className="v4-compose-sheet"><Link className="v4-sheet-backdrop" href={close} aria-label="Fermer"/><section className="v4-bottom-sheet" role="dialog" aria-modal="true"><div className="v4-sheet-handle"/><div className="v4-sheet-heading"><div><span className="v4-eyebrow">Famille</span><h2>Ajouter un enfant</h2></div><Link href={close} className="v4-icon-button" aria-label="Fermer"><Icon name="close"/></Link></div><form className="v4-form" action={addChildAction}><input type="hidden" name="spaceId" value={spaceId}/><div className="v4-form-row"><div className="v4-field"><label>Prénom</label><input name="firstName" required autoFocus/></div><div className="v4-field"><label>Date de naissance</label><input type="date" name="birthDate"/></div></div><div className="v4-field"><label>École / crèche</label><input name="school" placeholder="Nom, classe, adresse utile…"/></div><div className="v4-field"><label>Allergies / points de vigilance</label><textarea name="allergies" rows={2}/></div><div className="v4-field"><label>Habitudes utiles</label><textarea name="habits" rows={2} placeholder="Doudou, rituel du soir…"/></div><div className="v4-field"><label>Contacts d’urgence</label><textarea name="emergencyContacts" rows={2} placeholder="Nom + téléphone"/></div><button className="btn brandbtn full">Ajouter</button></form></section></div>}
function Info({label,value}:{label:string;value:string|null}){return <div className="v5-child-info"><strong>{label}</strong><span>{value||"Non renseigné"}</span></div>}
export function ChildrenPanel({spaceId,children,canEdit,q,compose}:{spaceId:string;children:Child[];canEdit:boolean;q:Query;compose?:string}){return <div className="v4-stack"><PageTitle eyebrow="Famille" title="Enfants" description="Les informations réellement utiles aux adultes qui s’en occupent." action={canEdit?<Link className="btn brandbtn" href={q({section:"more",area:"children",compose:"child"})}><Icon name="plus"/> Ajouter</Link>:undefined}/>{children.length?<div className="v4-grid-2">{children.map(child=><Card key={child.id}><div className="v4-profile-hero"><Avatar name={child.firstName} size="lg"/><div><h2>{child.firstName}</h2><p>{ageLabel(child.birthDate)}</p></div></div>{child.allergies&&<div className="v5-alert"><strong>À connaître</strong><span>{child.allergies}</span></div>}<div className="v5-child-grid"><Info label="École / crèche" value={child.school}/><Info label="Habitudes" value={child.habits}/><Info label="Contacts d’urgence" value={child.emergencyContacts}/><Info label="Autres informations" value={child.notes}/></div>{canEdit&&<details className="v4-profile-settings"><summary>Modifier le profil <Icon name="chevronRight" size={17}/></summary><form className="v4-form" action={updateChildAction}><input type="hidden" name="spaceId" value={spaceId}/><input type="hidden" name="childId" value={child.id}/><div className="v4-form-row"><div className="v4-field"><label>Prénom</label><input name="firstName" defaultValue={child.firstName} required/></div><div className="v4-field"><label>Date de naissance</label><input type="date" name="birthDate" defaultValue={child.birthDate||""}/></div></div><div className="v4-field"><label>École / crèche</label><input name="school" defaultValue={child.school||""}/></div><div className="v4-field"><label>Allergies / vigilance</label><textarea name="allergies" defaultValue={child.allergies||""}/></div><div className="v4-field"><label>Habitudes</label><textarea name="habits" defaultValue={child.habits||""}/></div><div className="v4-field"><label>Contacts d’urgence</label><textarea name="emergencyContacts" defaultValue={child.emergencyContacts||""}/></div><div className="v4-field"><label>Autres informations</label><textarea name="notes" defaultValue={child.notes||""}/></div><button className="btn primary full">Enregistrer</button></form></details>}</Card>)}</div>:<Card><EmptyState title="Ajoutez votre premier enfant" description="Son planning, ses consignes et son journal seront ensuite visibles au même endroit." icon="child"/></Card>}{compose==="child"&&<AddChildSheet spaceId={spaceId} q={q}/>}</div>}
