import Link from "next/link";
import { inArray } from "drizzle-orm";
import type { members } from "@/db/schema";
import { db } from "@/db";
import * as s from "@/db/schema";
import { spaceSnapshot } from "@/lib/data";
import { Icon, type IconName } from "@/components/ui/icons";
import { Avatar, Card, EmptyState, PageTitle, StatusBadge } from "@/components/ui/primitives";
import { activityIcon, journalIcon } from "@/lib/v4-presentation";
import { dateLabel } from "./utils";

type Snapshot=Awaited<ReturnType<typeof spaceSnapshot>>;type Member=typeof members.$inferSelect;type Query=(extra:Record<string,string>)=>string;type JournalProps={selectedDate:string;snapshot:Snapshot;team:Member[];memberName:(member:Member)=>string;canEditActivities:boolean;q:Query};const labels:Record<string,string>={MEAL:"Repas",MOOD:"Humeur",ACTIVITY:"Activité",NAP:"Sieste",NOTE:"Note",TOILET:"Toilette",MEDICINE:"Médicament",INCIDENT:"Incident"};
function Multiline({text}:{text:string}){return <>{text.split("\n").map((line,index)=><span key={`${index}-${line}`}>{index>0&&<br/>}{line||" "}</span>)}</>}
export async function Journal({selectedDate,snapshot,team,memberName,canEditActivities,q}:JournalProps){
  const resolved=snapshot.program.filter(item=>item.status==="DONE"||item.status==="NOT_DONE");const ids=resolved.map(item=>item.id);const programLinks=ids.length?await db.select().from(s.programChildren).where(inArray(s.programChildren.programItemId,ids)):[];const assigneeLinks=ids.length?await db.select().from(s.programAssignees).where(inArray(s.programAssignees.programItemId,ids)):[];const childNames=(itemId:string)=>programLinks.filter(link=>link.programItemId===itemId).map(link=>snapshot.children.find(child=>child.id===link.childId)?.firstName).filter(Boolean).join(", ");const memberById=(id:string|null)=>id?team.find(item=>item.id===id):undefined;const actorMemberId=(item:Snapshot["program"][number])=>{if(item.completedByMemberId)return item.completedByMemberId;const assigned=[...new Set(assigneeLinks.filter(link=>link.programItemId===item.id).map(link=>link.memberId))];return assigned.length===1?assigned[0]:null;};
  const entries=[...resolved.map(item=>({id:`p-${item.id}`,type:"activity" as const,itemId:item.id,icon:activityIcon(item.type,item.title),title:item.title,body:item.status==="NOT_DONE"?(item.note||"Prévu mais non réalisé"):[item.description,item.note].filter(Boolean).join("\n")||"Activité réalisée",child:childNames(item.id)||undefined,author:memberById(actorMemberId(item)),authorLabel:item.status==="DONE"?"Réalisé par":"Signalé par",outcome:item.status==="NOT_DONE"?(item.note?.startsWith("Remplacé par")?"Adapté":"Non fait"):null,at:item.completedAt||item.actualEnd||item.actualStart||new Date(`${selectedDate}T${item.plannedStart||"00:00"}:00`),editable:canEditActivities})),...snapshot.notes.map(note=>({id:`n-${note.id}`,type:"legacy" as const,itemId:null,icon:journalIcon(note.kind),title:labels[note.kind]||note.kind,body:[note.value,note.comment].filter(Boolean).join("\n"),child:snapshot.children.find(child=>child.id===note.childId)?.firstName,author:memberById(note.memberId),authorLabel:"Ajouté par",outcome:null,at:note.createdAt,editable:false})),...snapshot.handovers.map(handover=>({id:`h-${handover.id}`,type:"handover" as const,itemId:null,icon:"handover" as IconName,title:"Résumé de garde",body:handover.text,child:undefined,author:memberById(handover.fromMemberId),authorLabel:"Transmis par",outcome:null,at:handover.createdAt,editable:false}))].sort((a,b)=>new Date(b.at).getTime()-new Date(a.at).getTime());
  return <div className="v4-stack"><PageTitle eyebrow="Journal" title={dateLabel(selectedDate)} description="Le résumé de ce qui s’est passé, avec les adaptations utiles — pas un suivi minute par minute."/><Card>{entries.length?<div className="v4-journal">{entries.map(entry=><article className="v4-journal-entry" key={entry.id}><span className="v4-journal-icon"><Icon name={entry.icon}/></span><div><div className="v4-journal-meta"><time>{new Intl.DateTimeFormat("fr-FR",{hour:"2-digit",minute:"2-digit"}).format(new Date(entry.at))}</time>{entry.type==="handover"&&<StatusBadge tone="brand">Fin de garde</StatusBadge>}{entry.outcome&&<StatusBadge tone={entry.outcome==="Adapté"?"brand":"neutral"}>{entry.outcome}</StatusBadge>}{entry.child&&<StatusBadge>{entry.child}</StatusBadge>}{entry.editable&&entry.itemId&&<Link className="v4-text-action" href={q({section:"journal",compose:`activity-edit-${entry.itemId}`})}>Modifier</Link>}</div><h3>{entry.title}</h3><strong><Multiline text={entry.body}/></strong>{entry.author&&<div className="v4-journal-meta v4-journal-author"><Avatar name={memberName(entry.author)} size="sm"/><span>{entry.authorLabel} {memberName(entry.author)}</span></div>}</div></article>)}</div>:<EmptyState title="Le journal est encore vide" description="Il se remplit avec les transmissions et les activités réellement confirmées." icon="journal"/>}</Card></div>;
}
