import { and, asc, eq } from "drizzle-orm";
import { db } from "@/db";
import * as s from "@/db/schema";
import type { members as membersTable } from "@/db/schema";
import { EXCEPTION_SHIFT_NOTE } from "@/lib/coherence";
import { CARE_PERIOD_PREFIX, DAY_OFF_SHIFT_NOTE, parseCarePeriodNote, schoolYearPeriod, weekdayFromIso } from "@/lib/care-schedule";
import { CareScheduleEditor, type CareDayInput, type CareException, type CareDayOff } from "@/components/app/care-schedule-editor";
import { Avatar, Card, SectionHeader } from "@/components/ui/primitives";
import { Icon } from "@/components/ui/icons";

type Member=typeof membersTable.$inferSelect;const weekdays:[number,string][]=[[1,"Lundi"],[2,"Mardi"],[3,"Mercredi"],[4,"Jeudi"],[5,"Vendredi"],[6,"Samedi"],[0,"Dimanche"]];function compactDate(date:string){return new Intl.DateTimeFormat("fr-FR",{day:"numeric",month:"short",year:"numeric"}).format(new Date(`${date}T12:00:00`));}
export async function PlanningCareSchedules({spaceId,caregivers,selectedDate,memberName,compose}:{spaceId:string;caregivers:Member[];selectedDate:string;memberName:(member:Member)=>string;compose?:string}){
  if(!caregivers.length)return null;const [scheduleRules,shifts]=await Promise.all([db.select().from(s.scheduleRules).where(eq(s.scheduleRules.careSpaceId,spaceId)),db.select().from(s.shifts).where(eq(s.shifts.careSpaceId,spaceId)).orderBy(asc(s.shifts.shiftDate))]);
  return <Card className="v53-planning-care"><SectionHeader title="Horaires de garde" eyebrow="Semaine type + exceptions"/><p className="v4-form-help">Définissez une période une seule fois, puis ajustez seulement les dates exceptionnelles.</p><div className="v53-caregivers">{caregivers.map(member=>{const memberShifts=shifts.filter(shift=>shift.memberId===member.id);const recurring=memberShifts.filter(shift=>shift.status==="PLANNED"&&shift.note?.startsWith(CARE_PERIOD_PREFIX));const savedPeriod=recurring.map(shift=>parseCarePeriodNote(shift.note)).find(Boolean)||schoolYearPeriod(selectedDate);const memberRules=scheduleRules.filter(rule=>rule.memberId===member.id);const initialDays:CareDayInput[]=weekdays.map(([weekday,label])=>{const rule=memberRules.find(candidate=>candidate.weekday===weekday);const generated=recurring.find(shift=>weekdayFromIso(shift.shiftDate)===weekday);return {weekday,label,active:Boolean(rule||generated),start:rule?.startTime||generated?.plannedStart||"16:00",end:rule?.endTime||generated?.plannedEnd||"19:00"};});const exceptions:CareException[]=memberShifts.filter(shift=>shift.status==="PLANNED"&&shift.note===EXCEPTION_SHIFT_NOTE).map(shift=>({id:shift.id,date:shift.shiftDate,start:shift.plannedStart,end:shift.plannedEnd}));const daysOff:CareDayOff[]=memberShifts.filter(shift=>shift.status==="CANCELLED"||shift.note===DAY_OFF_SHIFT_NOTE).map(shift=>({id:shift.id,date:shift.shiftDate,start:shift.plannedStart,end:shift.plannedEnd}));const active=initialDays.filter(day=>day.active);const summary=active.length?`${active.map(day=>day.label.slice(0,3)).join(" · ")} · ${compactDate(savedPeriod.start)} → ${compactDate(savedPeriod.end)}`:"Horaires à configurer";return <details className="v53-caregiver-schedule" key={member.id} open={caregivers.length===1||compose==="shift"}><summary><Avatar name={memberName(member)} size="sm"/><span><strong>{memberName(member)}</strong><small>{summary}</small></span><Icon name="chevronRight" size={18}/></summary><CareScheduleEditor spaceId={spaceId} memberId={member.id} selectedDate={selectedDate} periodStart={savedPeriod.start} periodEnd={savedPeriod.end} initialDays={initialDays} exceptions={exceptions} daysOff={daysOff} defaultOpen={compose==="shift"}/></details>})}</div></Card>;
}
