import Link from "next/link";
import type { members } from "@/db/schema";
import { spaceSnapshot } from "@/lib/data";
import { addProgramItemAction, addTaskAction, applyRoutineAction, updateProgramStatusAction, updateTaskStatusAction } from "@/app/actions/program";
import { Icon } from "@/components/ui/icons";
import { Card, EmptyState, IconButton, PageTitle, SectionHeader, StatusBadge } from "@/components/ui/primitives";
import { activityIcon, clockLabel, shiftIsoDate, shortDay } from "@/lib/v4-presentation";
import { dateLabel, today } from "./utils";

type Snapshot=Awaited<ReturnType<typeof spaceSnapshot>>;
type Member=typeof members.$inferSelect;
type Query=(extra:Record<string,string>)=>string;

type PlanningProps={spaceId:string;selectedDate:string;snapshot:Snapshot;caregivers:Member[];children:Snapshot["children"];routines:{id:string;name:string}[];memberName:(member:Member)=>string;canEditProgram:boolean;canEditTasks:boolean;canActProgram:boolean;canActTasks:boolean;q:Query;timezone:string;compose?:string};

function WeekStrip({selectedDate,q}:{selectedDate:string;q:Query}){
  const dates=Array.from({length:7},(_,index)=>shiftIsoDate(selectedDate,index-3));
  return <div className="v4-week-strip" aria-label="Semaine autour de la date sélectionnée">{dates.map(date=><Link key={date} href={q({section:"planning",date})} className={date===selectedDate?"is-active":""}><small>{shortDay(date).split(" ")[0]}</small><strong>{new Date(`${date}T12:00:00`).getDate()}</strong></Link>)}</div>;
}

function ComposeSheet({kind,spaceId,date,children,caregivers,routines,memberName,q}:{kind:string;spaceId:string;date:string;children:Snapshot["children"];caregivers:Member[];routines:{id:string;name:string}[];memberName:(member:Member)=>string;q:Query}){
  const close=q({section:"planning",date,compose:""});
  const shell=(title:string,body:React.ReactNode)=><div className="v4-compose-sheet"><Link className="v4-sheet-backdrop" href={close} aria-label="Fermer"/><section className="v4-bottom-sheet" role="dialog" aria-modal="true"><div className="v4-sheet-handle"/><div className="v4-sheet-heading"><div><span className="v4-eyebrow">{dateLabel(date)}</span><h2>{title}</h2></div><Link href={close} className="v4-icon-button" aria-label="Fermer"><Icon name="close"/></Link></div>{body}</section></div>;
  if(kind==="activity")return shell("Ajouter une activité",<form className="v4-form" action={addProgramItemAction}><input type="hidden" name="spaceId" value={spaceId}/><input type="hidden" name="date" value={date}/><div className="v4-field"><label>Activité</label><input name="title" required autoFocus placeholder="Piscine, goûter, école…"/></div><div className="v4-form-row"><div className="v4-field"><label>Début</label><input name="start" type="time"/></div><div className="v4-field"><label>Fin</label><input name="end" type="time"/></div></div><div className="v4-field"><label>Type</label><select name="type"><option>Activité</option><option>École</option><option>Repas</option><option>Parc</option><option>Piscine</option><option>Sieste</option><option>Bain</option><option>Coucher</option><option>Rendez-vous</option><option>Autre</option></select></div><details className="v4-more-options"><summary>Plus d’options</summary><div className="v4-form"><div className="v4-field"><label>Description</label><textarea name="description"/></div><div className="v4-field"><label>Lieu</label><input name="location"/></div><div className="v4-field"><label>Enfant(s)</label><div className="v4-check-grid">{children.map(child=><label className="v4-check-row" key={child.id}><input type="checkbox" name="childIds" value={child.id}/>{child.firstName}</label>)}</div></div><div className="v4-field"><label>Intervenant(s)</label><div className="v4-check-grid">{caregivers.map(member=><label className="v4-check-row" key={member.id}><input type="checkbox" name="memberIds" value={member.id}/>{memberName(member)}</label>)}</div></div></div></details><button className="btn brandbtn full">Créer l’activité</button></form>);
  if(kind==="task")return shell("Ajouter une tâche",<form className="v4-form" action={addTaskAction}><input type="hidden" name="spaceId" value={spaceId}/><input type="hidden" name="date" value={date}/><div className="v4-field"><label>Titre</label><input name="title" required autoFocus placeholder="Préparer le sac de piscine"/></div><div className="v4-field"><label>Heure</label><input name="time" type="time"/></div><div className="v4-field"><label>Enfant(s)</label><div className="v4-check-grid">{children.map(child=><label className="v4-check-row" key={child.id}><input type="checkbox" name="childIds" value={child.id}/>{child.firstName}</label>)}</div></div><div className="v4-field"><label>Intervenant(s)</label><div className="v4-check-grid">{caregivers.map(member=><label className="v4-check-row" key={member.id}><input type="checkbox" name="memberIds" value={member.id}/>{memberName(member)}</label>)}</div></div><button className="btn brandbtn full">Créer la tâche</button></form>);
  if(kind==="routine"&&routines.length)return shell("Appliquer une routine",<form className="v4-form" action={applyRoutineAction}><input type="hidden" name="spaceId" value={spaceId}/><input type="hidden" name="date" value={date}/><div className="v4-field"><label>Routine</label><select name="routineId">{routines.map(routine=><option key={routine.id} value={routine.id}>{routine.name}</option>)}</select></div><div className="v4-field"><label>Intervenant</label><select name="memberId">{caregivers.map(member=><option key={member.id} value={member.id}>{memberName(member)}</option>)}</select></div><div className="v4-field"><label>Enfant</label><select name="childId">{children.map(child=><option key={child.id} value={child.id}>{child.firstName}</option>)}</select></div><button className="btn brandbtn full">Ajouter au planning</button></form>);
  return null;
}

export function Planning({spaceId,selectedDate,snapshot,caregivers,children,routines,memberName,canEditProgram,canEditTasks,canActProgram,canActTasks,q,timezone,compose}:PlanningProps){
  const todayIso=today(timezone);const canRealize=selectedDate<=todayIso;
  const entries=[...snapshot.program.map(item=>({id:item.id,kind:"program" as const,time:item.plannedStart,title:item.title,subtitle:item.description||item.location||item.type,status:item.status,icon:activityIcon(item.type,item.title),actual:[clockLabel(item.actualStart),clockLabel(item.actualEnd)].filter(Boolean).join("–"),end:item.plannedEnd})),...snapshot.tasks.map(item=>({id:item.id,kind:"task" as const,time:item.time,title:item.title,subtitle:item.description||item.note||"Tâche",status:item.status,icon:activityIcon("tâche",item.title),actual:"",end:null}))].sort((a,b)=>(a.time||"99:99").localeCompare(b.time||"99:99"));
  const mode=selectedDate===todayIso?"Aujourd’hui":selectedDate<todayIso?"Historique":"À venir";
  return <div className="v4-stack"><PageTitle eyebrow="Planning" title={dateLabel(selectedDate)} description="La journée, les relais et les tâches dans un seul fil."/>
    <Card className="v4-planning-nav"><div className="v4-date-nav"><IconButton href={q({section:"planning",date:shiftIsoDate(selectedDate,-1)})} label="Jour précédent" icon="chevronLeft"/><div className="v4-date-current"><strong>{mode}</strong>{selectedDate!==todayIso&&<Link className="v4-text-action" href={q({section:"planning",date:todayIso})}>Revenir à aujourd’hui</Link>}</div><IconButton href={q({section:"planning",date:shiftIsoDate(selectedDate,1)})} label="Jour suivant" icon="chevronRight"/></div><WeekStrip selectedDate={selectedDate} q={q}/></Card>

    <Card><SectionHeader title="Journée" eyebrow={`${entries.length} élément${entries.length>1?"s":""}`}/>{entries.length?<div className="v4-timeline">{entries.map(entry=>{const done=entry.status==="DONE";const act=entry.kind==="program"?canActProgram:canActTasks;return <div className={`v4-timeline-item ${done?"is-done":""}`} key={`${entry.kind}-${entry.id}`}><time className="v4-timeline-time">{entry.time||"—"}</time><span className="v4-timeline-rail"><span className="v4-timeline-icon"><Icon name={entry.icon} size={18}/></span></span><span className="v4-timeline-copy"><strong>{entry.title}</strong><small>{done&&entry.actual?`Réalisé ${entry.actual}`:entry.subtitle}</small></span><span className="v4-timeline-action">{done?<StatusBadge tone="success">Fait</StatusBadge>:entry.status==="NOT_DONE"?<StatusBadge tone="danger">Non fait</StatusBadge>:canRealize&&act?(entry.kind==="program"?<form action={updateProgramStatusAction}><input type="hidden" name="spaceId" value={spaceId}/><input type="hidden" name="itemId" value={entry.id}/><input type="hidden" name="status" value="DONE"/><input type="hidden" name="actualStart" value={entry.time||""}/><input type="hidden" name="actualEnd" value={entry.end||entry.time||""}/><button className="v4-check-button" aria-label={`Terminer ${entry.title}`}><Icon name="check"/></button></form>:<form action={updateTaskStatusAction}><input type="hidden" name="spaceId" value={spaceId}/><input type="hidden" name="taskId" value={entry.id}/><input type="hidden" name="status" value="DONE"/><button className="v4-check-button" aria-label={`Terminer ${entry.title}`}><Icon name="check"/></button></form>):<StatusBadge>Prévu</StatusBadge>}</span></div>})}</div>:<EmptyState title="Rien de prévu ce jour" description="Ajoutez seulement ce qui mérite d’être partagé." icon="calendar"/>}</Card>

    {(canEditProgram||canEditTasks)&&<div className="v4-inline-actions">{canEditProgram&&<Link className="btn soft" href={q({section:"planning",compose:"activity"})}><Icon name="activity"/> Activité</Link>}{canEditTasks&&<Link className="btn soft" href={q({section:"planning",compose:"task"})}><Icon name="task"/> Tâche</Link>}{canEditTasks&&routines.length>0&&<Link className="btn soft" href={q({section:"planning",compose:"routine"})}><Icon name="moon"/> Routine</Link>}</div>}
    {compose&&<ComposeSheet kind={compose} spaceId={spaceId} date={selectedDate} children={children} caregivers={caregivers} routines={routines} memberName={memberName} q={q}/>} 
  </div>;
}
