import { asc, inArray } from "drizzle-orm";
import type { children as childrenTable, members as membersTable, routines as routinesTable } from "@/db/schema";
import { db } from "@/db";
import * as s from "@/db/schema";
import { addRoutineAction } from "@/app/actions/program";
import { applyRoutineToPlanningAction, deleteRoutineAction, updateRoutineAction } from "@/app/actions/management";
import { Icon } from "@/components/ui/icons";
import { Card, EmptyState, SectionHeader } from "@/components/ui/primitives";

type Child=typeof childrenTable.$inferSelect;type Member=typeof membersTable.$inferSelect;type Routine=typeof routinesTable.$inferSelect;
export async function PlanningRoutines({spaceId,selectedDate,routines,children,caregivers,memberName,canApply,canManage}:{spaceId:string;selectedDate:string;routines:Routine[];children:Child[];caregivers:Member[];memberName:(member:Member)=>string;canApply:boolean;canManage:boolean}){
  if(!canApply&&!canManage)return null;
  const items=routines.length?await db.select().from(s.routineItems).where(inArray(s.routineItems.routineId,routines.map(routine=>routine.id))).orderBy(asc(s.routineItems.position)):[];
  return <Card tone="soft"><SectionHeader title="Routines" eyebrow="Ajouter en un geste"/>{routines.length&&canApply?<div className="v5-routine-quick">{routines.map(routine=><form key={routine.id} action={applyRoutineToPlanningAction}><input type="hidden" name="spaceId" value={spaceId}/><input type="hidden" name="routineId" value={routine.id}/><input type="hidden" name="date" value={selectedDate}/><span><strong>{routine.name}</strong><small>{routine.description||items.filter(item=>item.routineId===routine.id).map(item=>item.title).join(" → ")||"Ajoute toutes les étapes au planning"}</small></span><input type="time" name="start" defaultValue="18:00" aria-label={`Heure de début de ${routine.name}`}/>{children.length===1?<input type="hidden" name="childId" value={children[0].id}/>:<select name="childId" aria-label="Enfant"><option value="">Tous</option>{children.map(child=><option value={child.id} key={child.id}>{child.firstName}</option>)}</select>}{caregivers.length===1?<input type="hidden" name="memberId" value={caregivers[0].id}/>:<select name="memberId" aria-label="Intervenant"><option value="">Non assigné</option>{caregivers.map(member=><option value={member.id} key={member.id}>{memberName(member)}</option>)}</select>}<button className="btn brandbtn">Ajouter</button></form>)}</div>:!routines.length?<EmptyState title="Aucune routine" description="Créez votre première routine pour ajouter plusieurs activités en un geste." icon="moon"/>:null}
    {canManage&&<details className="v4-advanced-details v56-routine-manager"><summary><span><Icon name="settings"/> Gérer les routines</span><Icon name="chevronRight" size={17}/></summary><div className="v4-stack"><form className="v4-form" action={addRoutineAction}><input type="hidden" name="spaceId" value={spaceId}/><div className="v4-form-row"><div className="v4-field"><label>Nom</label><input name="name" required placeholder="Routine du soir"/></div><div className="v4-field"><label>Description <span className="muted">· facultatif</span></label><input name="description" placeholder="Après l’école…"/></div></div><div className="v4-field"><label>Étapes · une par ligne</label><textarea name="items" required rows={4} placeholder={'Dîner\nToilette\nBrosser les dents\nHistoire\nCoucher'}/></div><button className="btn soft full">Créer une routine</button></form>{routines.map(routine=>{const lines=items.filter(item=>item.routineId===routine.id).map(item=>item.title);return <details className="v5-routine-edit" key={routine.id}><summary><span className="v4-row-icon"><Icon name="moon"/></span><span className="v4-row-copy"><strong>{routine.name}</strong><small>{lines.join(" → ")||routine.description||"Routine vide"}</small></span><Icon name="chevronRight" size={17}/></summary><form className="v4-form" action={updateRoutineAction}><input type="hidden" name="spaceId" value={spaceId}/><input type="hidden" name="routineId" value={routine.id}/><div className="v4-field"><label>Nom</label><input name="name" defaultValue={routine.name}/></div><div className="v4-field"><label>Description</label><input name="description" defaultValue={routine.description||""}/></div><div className="v4-field"><label>Étapes · une par ligne</label><textarea name="items" defaultValue={lines.join("\n")} rows={4}/></div><div className="v5-inline-buttons"><button className="btn primary">Enregistrer</button><button className="btn danger" formAction={deleteRoutineAction}>Supprimer</button></div></form></details>})}</div></details>}
  </Card>;
}
