"use client";
import { useEffect, useState } from "react";

function toApplicationServerKey(value:string):ArrayBuffer{const pad="=".repeat((4-value.length%4)%4);const base=(value+pad).replace(/-/g,"+").replace(/_/g,"/");const raw=atob(base);const bytes=Uint8Array.from([...raw].map(char=>char.charCodeAt(0)));return bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer;}
export function PushSettings(){
  const [supported,setSupported]=useState(false),[enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  useEffect(()=>{setSupported("serviceWorker" in navigator&&"PushManager" in window&&"Notification" in window);navigator.serviceWorker?.getRegistration().then(reg=>reg?.pushManager.getSubscription()).then(sub=>setEnabled(Boolean(sub))).catch(()=>{});},[]);
  async function enable(){setBusy(true);setMessage("");try{const permission=await Notification.requestPermission();if(permission!=="granted")throw new Error("Autorisation refusée");const registration=await navigator.serviceWorker.register("/sw.js");await navigator.serviceWorker.ready;const response=await fetch("/api/push/public-key");if(!response.ok)throw new Error("Clé de notification indisponible");const {publicKey}=await response.json();let subscription=await registration.pushManager.getSubscription();if(!subscription)subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:toApplicationServerKey(publicKey)});const saved=await fetch("/api/push/subscribe",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(subscription.toJSON())});if(!saved.ok)throw new Error("Enregistrement impossible");setEnabled(true);setMessage("Notifications activées.");}catch(error:any){setMessage(error?.message||"Impossible d’activer les notifications.");}finally{setBusy(false);}}
  async function disable(){setBusy(true);try{const registration=await navigator.serviceWorker.getRegistration();const subscription=await registration?.pushManager.getSubscription();if(subscription){await fetch("/api/push/subscribe",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({endpoint:subscription.endpoint})});await subscription.unsubscribe();}setEnabled(false);setMessage("Notifications désactivées sur cet appareil.");}finally{setBusy(false);}}
  if(!supported)return <p className="v5-help">Les notifications système ne sont pas disponibles dans ce navigateur. Sur iPhone, installez d’abord Nanny Youpiii sur l’écran d’accueil.</p>;
  return <div className="v5-push-row"><div><strong>{enabled?"Notifications système activées":"Notifications système désactivées"}</strong><small>Recevez les activités terminées, messages et fins de garde même lorsque l’application est fermée.</small>{message&&<em>{message}</em>}</div><button type="button" className={`btn ${enabled?"soft":"brandbtn"}`} disabled={busy} onClick={enabled?disable:enable}>{busy?"…":enabled?"Désactiver":"Activer"}</button></div>;
}
