import Link from "next/link";
import { and, asc, eq, gte, lte } from "drizzle-orm";
import { db } from "@/db";
import * as s from "@/db/schema";
import { isParentRole } from "@/lib/security";
import { Card, EmptyState, PageTitle } from "@/components/ui/primitives";

type Member=typeof s.members.$inferSelect;
function monthBounds(month:string){const [year,m]=month.split("-").map(Number);const last=new Date(Date.UTC(year,m,0)).getUTCDate();return {start:`${month}-01`,end:`${month}-${String(last).padStart(2,"0")}`};}
function duration(start:Date|null,end:Date|null,plannedStart:string,plannedEnd:string){if(start&&end)return Math.max(0,(end.getTime()-start.getTime())/3600000);const [sh,sm]=plannedStart.split(":").map(Number),[eh,em]=plannedEnd.split(":").map(Number);return Math.max(0,(eh*60+em-sh*60-sm)/60);}
export async function ReportsPanel({spaceId,currentMember,team,memberName,month}:{spaceId:string;currentMember:Member;team:Member[];memberName:(member:Member)=>string;month:string}){
  const {start,end}=monthBounds(month);let shifts=await db.select().from(s.shifts).where(and(eq(s.shifts.careSpaceId,spaceId),gte(s.shifts.shiftDate,start),lte(s.shifts.shiftDate,end))).orderBy(asc(s.shifts.shiftDate),asc(s.shifts.plannedStart));if(!isParentRole(currentMember.role))shifts=shifts.filter(shift=>shift.memberId===currentMember.id);const rows=team.filter(member=>isParentRole(currentMember.role)?!isParentRole(member.role):member.id===currentMember.id).map(member=>{const mine=shifts.filter(shift=>shift.memberId===member.id&&shift.status!=="CANCELLED");const hours=mine.reduce((sum,shift)=>sum+duration(shift.actualStart,shift.actualEnd,shift.plannedStart,shift.plannedEnd),0);const realized=mine.filter(shift=>shift.status==="ENDED").length;return {member,hours,shifts:mine.length,realized};});
  return <div className="v4-stack"><PageTitle eyebrow="Suivi" title="Heures & export" description="Un récapitulatif simple des gardes du mois, sans essayer de remplacer Pajemploi."/><Card><form className="v5-month-switch" method="get"><input type="hidden" name="space" value={spaceId}/><input type="hidden" name="section" value="more"/><input type="hidden" name="area" value="reports"/><label>Mois <input type="month" name="month" defaultValue={month}/></label><button className="btn soft">Afficher</button><Link className="btn brandbtn" href={`/api/export/monthly?space=${encodeURIComponent(spaceId)}&month=${month}`}>Exporter CSV</Link></form></Card><Card>{rows.length?<div className="v5-report-list">{rows.map(row=><div className="v5-report-row" key={row.member.id}><span><strong>{memberName(row.member)}</strong><small>{row.realized}/{row.shifts} garde{row.shifts>1?"s":""} terminée{row.realized>1?"s":""}</small></span><b>{row.hours.toFixed(2).replace(".",",")} h</b></div>)}</div>:<EmptyState title="Aucune garde ce mois" description="Le récapitulatif apparaîtra dès qu’un horaire de garde est planifié." icon="calendar"/>}</Card><p className="v5-help">Les heures réelles sont utilisées lorsqu’une garde a été commencée/terminée dans l’application ; sinon les horaires prévus servent d’estimation.</p></div>;
}
