import Link from "next/link";
import type { members as membersTable } from "@/db/schema";
import { spaceSnapshot } from "@/lib/data";
import { addInstructionAction } from "@/app/actions/program";
import { deleteInstructionAction, updateInstructionAction } from "@/app/actions/management";
import { Icon } from "@/components/ui/icons";
import { Card, EmptyState, PageTitle, StatusBadge } from "@/components/ui/primitives";

type Snapshot=Awaited<ReturnType<typeof spaceSnapshot>>;type Member=typeof membersTable.$inferSelect;type Query=(extra:Record<string,string>)=>string;type Routine={id:string;name:string;description:string|null};
function RecipientFields({children,team,childIds=[],memberIds=[]}:{children:Snapshot["children"];team:Member[];childIds?:string[];memberIds?:string[]}){return <div className="v4-form"><div className="v4-field"><label>Enfants</label><div className="v4-check-grid">{children.map(child=><label key={child.id} className="v4-check-row"><input type="checkbox" name="childIds" value={child.id} defaultChecked={childIds.includes(child.id)}/>{child.firstName}</label>)}</div></div><div className="v4-field"><label>Intervenants spécifiques <span className="muted">· aucun = tous</span></label><div className="v4-check-grid">{team.filter(member=>!member.role.startsWith("PARENT")).map(member=><label key={member.id} className="v4-check-row"><input type="checkbox" name="memberIds" value={member.id} defaultChecked={memberIds.includes(member.id)}/>{member.label||member.role}</label>)}</div></div></div>}
function InstructionSheet({spaceId,children,team,q}:{spaceId:string;children:Snapshot["children"];team:Member[];q:Query}){const close=q({section:"more",area:"rules",compose:""});return <div className="v4-compose-sheet"><Link className="v4-sheet-backdrop" href={close} aria-label="Fermer"/><section className="v4-bottom-sheet" role="dialog" aria-modal="true"><div className="v4-sheet-handle"/><div className="v4-sheet-heading"><div><span className="v4-eyebrow">Consignes</span><h2>Ajouter une consigne</h2></div><Link className="v4-icon-button" href={close} aria-label="Fermer"><Icon name="close"/></Link></div><form className="v4-form" action={addInstructionAction}><input type="hidden" name="spaceId" value={spaceId}/><div className="v4-field"><label>Type</label><select name="kind"><option value="IMPORTANT">Important</option><option value="FORBIDDEN">Interdit</option><option value="ALLOWED">Autorisé</option><option value="HABIT">Habitude</option></select></div><div className="v4-field"><label>Consigne</label><textarea name="text" required autoFocus placeholder="Pas de vidéos le soir…"/></div><div className="v4-field"><label>Date si ponctuelle</label><input name="validOn" type="date"/></div><details className="v4-more-options"><summary>Destinataires</summary><RecipientFields children={children} team={team}/></details><button className="btn brandbtn full">Enregistrer</button></form></section></div>}
export async function RulesPanel({spaceId,snapshot,team,routines: _routines,canManage,q,compose}:{spaceId:string;snapshot:Snapshot;team:Member[];routines:Routine[];canManage:boolean;q:Query;compose?:string}){void _routines;return <div className="v4-stack"><PageTitle eyebrow="Organisation" title="Consignes" description="Les règles importantes à partager avec les adultes qui s’occupent des enfants." action={canManage?<Link className="btn brandbtn" href={q({section:"more",area:"rules",compose:"instruction"})}><Icon name="plus"/> Consigne</Link>:undefined}/><Card>{snapshot.instructions.length?<div className="v4-instruction-list">{snapshot.instructions.map(item=><details className={`v5-editable-instruction ${item.kind==="FORBIDDEN"?"danger":item.kind==="IMPORTANT"?"warning":""}`} key={item.id}><summary><Icon name={item.kind==="FORBIDDEN"?"ban":item.kind==="IMPORTANT"?"alert":"headphones"}/><span>{item.text}</span><StatusBadge>{item.permanent?"Permanent":item.validOn||"Ponctuel"}</StatusBadge></summary>{canManage&&<form className="v4-form" action={updateInstructionAction}><input type="hidden" name="spaceId" value={spaceId}/><input type="hidden" name="instructionId" value={item.id}/><div className="v4-field"><label>Type</label><select name="kind" defaultValue={item.kind}><option value="IMPORTANT">Important</option><option value="FORBIDDEN">Interdit</option><option value="ALLOWED">Autorisé</option><option value="HABIT">Habitude</option></select></div><div className="v4-field"><label>Consigne</label><textarea name="text" defaultValue={item.text}/></div><div className="v4-field"><label>Date si ponctuelle</label><input name="validOn" type="date" defaultValue={item.validOn||""}/></div><RecipientFields children={snapshot.children} team={team} childIds={item.childIds} memberIds={item.memberIds}/><div className="v5-inline-buttons"><button className="btn primary">Enregistrer</button><button className="btn danger" formAction={deleteInstructionAction}>Supprimer</button></div></form>}</details>)}</div>:<EmptyState title="Aucune consigne" description="Ajoutez seulement les règles qui doivent vraiment être partagées." icon="alert"/>}</Card>{compose==="instruction"&&<InstructionSheet spaceId={spaceId} children={snapshot.children} team={team} q={q}/>}</div>}
