import Link from "next/link";
import type { members as membersTable } from "@/db/schema";
import { spaceSnapshot } from "@/lib/data";
import { addInstructionAction, addRoutineAction } from "@/app/actions/program";
import { Icon } from "@/components/ui/icons";
import { Card, EmptyState, PageTitle, SectionHeader, StatusBadge } from "@/components/ui/primitives";

type Snapshot=Awaited<ReturnType<typeof spaceSnapshot>>;type Member=typeof membersTable.$inferSelect;type Query=(extra:Record<string,string>)=>string;
type Routine={id:string;name:string;description:string|null};

function InstructionSheet({spaceId,children,team,q}:{spaceId:string;children:Snapshot["children"];team:Member[];q:Query}){const close=q({section:"more",area:"rules",compose:""});return <div className="v4-compose-sheet"><Link className="v4-sheet-backdrop" href={close} aria-label="Fermer"/><section className="v4-bottom-sheet" role="dialog" aria-modal="true"><div className="v4-sheet-handle"/><div className="v4-sheet-heading"><div><span className="v4-eyebrow">Consignes</span><h2>Ajouter une consigne</h2></div><Link className="v4-icon-button" href={close} aria-label="Fermer"><Icon name="close"/></Link></div><form className="v4-form" action={addInstructionAction}><input type="hidden" name="spaceId" value={spaceId}/><div className="v4-field"><label>Type</label><select name="kind"><option value="IMPORTANT">Important</option><option value="FORBIDDEN">Interdit</option><option value="ALLOWED">Autorisé</option><option value="HABIT">Habitude</option></select></div><div className="v4-field"><label>Consigne</label><textarea name="text" required autoFocus placeholder="Pas de vidéos le soir…"/></div><div className="v4-field"><label>Date si ponctuelle</label><input name="validOn" type="date"/></div><details className="v4-more-options"><summary>Destinataires</summary><div className="v4-form"><div className="v4-field"><label>Enfants</label><div className="v4-check-grid">{children.map(child=><label key={child.id} className="v4-check-row"><input type="checkbox" name="childIds" value={child.id}/>{child.firstName}</label>)}</div></div><div className="v4-field"><label>Intervenants spécifiques</label><div className="v4-check-grid">{team.filter(member=>!member.role.startsWith("PARENT")).map(member=><label key={member.id} className="v4-check-row"><input type="checkbox" name="memberIds" value={member.id}/>{member.label||member.role}</label>)}</div></div></div></details><button className="btn brandbtn full">Enregistrer</button></form></section></div>}

function RoutineSheet({spaceId,q}:{spaceId:string;q:Query}){const close=q({section:"more",area:"rules",compose:""});return <div className="v4-compose-sheet"><Link className="v4-sheet-backdrop" href={close} aria-label="Fermer"/><section className="v4-bottom-sheet"><div className="v4-sheet-handle"/><div className="v4-sheet-heading"><div><span className="v4-eyebrow">Routine</span><h2>Créer une routine</h2></div><Link href={close} className="v4-icon-button" aria-label="Fermer"><Icon name="close"/></Link></div><form className="v4-form" action={addRoutineAction}><input type="hidden" name="spaceId" value={spaceId}/><div className="v4-field"><label>Nom</label><input name="name" required autoFocus placeholder="Routine coucher"/></div><div className="v4-field"><label>Étapes · une par ligne</label><textarea name="items" required placeholder={'Dîner\nToilette\nBrosser les dents\nHistoire\nCoucher'}/></div><button className="btn brandbtn full">Créer la routine</button></form></section></div>}

export function RulesPanel({spaceId,snapshot,team,routines,canManage,q,compose}:{spaceId:string;snapshot:Snapshot;team:Member[];routines:Routine[];canManage:boolean;q:Query;compose?:string}){
  return <div className="v4-stack"><PageTitle eyebrow="Organisation" title="Consignes & routines" description="Ce qui doit être connu de tous, sans surcharger le planning." action={canManage?<Link className="btn brandbtn" href={q({section:"more",area:"rules",compose:"instruction"})}><Icon name="plus"/> Consigne</Link>:undefined}/><div className="v4-grid-2"><Card><SectionHeader title="Consignes"/>{snapshot.instructions.length?<div className="v4-instruction-list">{snapshot.instructions.map(item=><div className={`v4-instruction ${item.kind==="FORBIDDEN"?"danger":item.kind==="IMPORTANT"?"warning":""}`} key={item.id}><Icon name={item.kind==="FORBIDDEN"?"ban":item.kind==="IMPORTANT"?"alert":"headphones"}/><span>{item.text}</span><StatusBadge>{item.permanent?"Permanent":item.validOn||"Ponctuel"}</StatusBadge></div>)}</div>:<EmptyState title="Aucune consigne" description="Ajoutez seulement les règles qui doivent vraiment être partagées." icon="alert"/>}</Card><Card><SectionHeader title="Routines" action={canManage?<Link className="v4-text-action" href={q({section:"more",area:"rules",compose:"routine"})}>Créer</Link>:undefined}/>{routines.length?<div>{routines.map(routine=><div className="v4-list-row" key={routine.id}><span className="v4-row-icon"><Icon name="moon"/></span><span className="v4-row-copy"><strong>{routine.name}</strong><small>{routine.description||"Routine réutilisable dans le planning"}</small></span></div>)}</div>:<EmptyState title="Aucune routine" description="Une routine permet de réutiliser les mêmes étapes sans les ressaisir." icon="moon"/>}</Card></div>{compose==="instruction"&&<InstructionSheet spaceId={spaceId} children={snapshot.children} team={team} q={q}/>} {compose==="routine"&&<RoutineSheet spaceId={spaceId} q={q}/>}</div>;
}
