import Link from "next/link";
import type { invitations as invitationsTable, members as membersTable, children as childrenTable, memberChildren as memberChildrenTable, scheduleRules as scheduleRulesTable } from "@/db/schema";
import { inviteMemberAction, updateMemberAccessAction, cancelInvitationAction, resendInvitationAction } from "@/app/actions/space";
import { addShiftAction, saveScheduleRuleAction } from "@/app/actions/schedule";
import { isParentRole } from "@/lib/security";
import { Icon } from "@/components/ui/icons";
import { Avatar, Card, EmptyState, PageTitle, SectionHeader, StatusBadge } from "@/components/ui/primitives";
import { roleLabel } from "./utils";

type Member=typeof membersTable.$inferSelect;type Child=typeof childrenTable.$inferSelect;type Invitation=typeof invitationsTable.$inferSelect;type MemberChild=typeof memberChildrenTable.$inferSelect;type ScheduleRule=typeof scheduleRulesTable.$inferSelect;type Query=(extra:Record<string,string>)=>string;
type Props={spaceId:string;team:Member[];children:Child[];invitations:Invitation[];memberName:(member:Member)=>string;selectedDate:string;q:Query;scheduleRules:ScheduleRule[];memberChildLinks:MemberChild[];canAdmin:boolean;previewableMemberIds:Set<string>;compose?:string};
const permissions=[{key:"journal",label:"Journal",description:"Ajouter et lire les transmissions"},{key:"shopping",label:"Courses",description:"Voir et enregistrer les achats"},{key:"cash",label:"Caisse",description:"Voir le solde disponible"}] as const;

function PlanningSwitch({defaultChecked=true}:{defaultChecked?:boolean}){return <label className="v4-setting-row"><span><strong>Planning</strong><small>Voir ce qui est prévu et le marquer comme fait</small></span><span className="v4-switch"><input type="checkbox" name="planning" defaultChecked={defaultChecked}/><span/></span></label>}
function PermissionSwitches({includeChildren=false}:{includeChildren?:boolean}){return <div className="v4-settings-group">{includeChildren&&<label className="v4-setting-row"><span><strong>Gérer ses enfants</strong><small>Profil et organisation des enfants accessibles</small></span><span className="v4-switch"><input type="checkbox" name="children" defaultChecked/><span/></span></label>}<PlanningSwitch/>{permissions.map(permission=><label className="v4-setting-row" key={permission.key}><span><strong>{permission.label}</strong><small>{permission.description}</small></span><span className="v4-switch"><input type="checkbox" name={permission.key} defaultChecked/><span/></span></label>)}</div>}

function InviteSheet({spaceId,children,q}:{spaceId:string;children:Child[];q:Query}){const close=q({section:"more",area:"team",compose:""});return <div className="v4-compose-sheet"><Link className="v4-sheet-backdrop" href={close} aria-label="Fermer"/><section className="v4-bottom-sheet" role="dialog" aria-modal="true"><div className="v4-sheet-handle"/><div className="v4-sheet-heading"><div><span className="v4-eyebrow">Équipe</span><h2>Inviter une personne</h2></div><Link href={close} className="v4-icon-button" aria-label="Fermer"><Icon name="close"/></Link></div><form className="v4-form" action={inviteMemberAction}><input type="hidden" name="spaceId" value={spaceId}/><div className="v4-field"><label>E-mail</label><input name="email" type="email" required autoFocus placeholder="prenom@exemple.fr"/></div><div className="v4-field"><label>Rôle</label><select name="role"><option value="NANNY">Nounou</option><option value="BABYSITTER">Baby-sitter</option><option value="PARENT">Autre parent</option><option value="CAREGIVER">Autre intervenant</option></select></div><div className="v4-field"><label>Enfants accessibles</label><div className="v4-check-grid">{children.map(child=><label className="v4-check-row" key={child.id}><input type="checkbox" name="childIds" value={child.id}/>{child.firstName}</label>)}</div></div><div><span className="v4-eyebrow">Accès à l’arrivée</span><PermissionSwitches/><p className="v4-form-help">Planning regroupe activités et anciennes tâches. Courses donne automatiquement accès au solde de caisse nécessaire pour acheter.</p></div><button className="btn brandbtn full">Envoyer l’invitation</button></form></section></div>}

function ShiftSheet({spaceId,caregivers,date,memberName,q}:{spaceId:string;caregivers:Member[];date:string;memberName:(member:Member)=>string;q:Query}){const close=q({section:"more",area:"team",compose:""});return <div className="v4-compose-sheet"><Link className="v4-sheet-backdrop" href={close} aria-label="Fermer"/><section className="v4-bottom-sheet" role="dialog" aria-modal="true"><div className="v4-sheet-handle"/><div className="v4-sheet-heading"><div><span className="v4-eyebrow">Planning</span><h2>Ajouter une garde</h2></div><Link href={close} className="v4-icon-button" aria-label="Fermer"><Icon name="close"/></Link></div><form className="v4-form" action={addShiftAction}><input type="hidden" name="spaceId" value={spaceId}/><div className="v4-field"><label>Intervenant</label><select name="memberId">{caregivers.map(member=><option key={member.id} value={member.id}>{memberName(member)}</option>)}</select></div><div className="v4-field"><label>Date</label><input name="date" type="date" defaultValue={date}/></div><div className="v4-form-row"><div className="v4-field"><label>Début</label><input name="start" type="time" required/></div><div className="v4-field"><label>Fin</label><input name="end" type="time" required/></div></div><button className="btn brandbtn full">Ajouter la garde</button></form></section></div>}

export function TeamPanel({spaceId,team,children,invitations,memberName,selectedDate,q,scheduleRules,memberChildLinks,canAdmin,previewableMemberIds,compose}:Props){
  const caregivers=team.filter(member=>!isParentRole(member.role));
  return <div className="v4-stack"><PageTitle eyebrow="Famille" title="Équipe" description="Chaque adulte dispose uniquement des enfants et fonctions dont il a besoin." action={canAdmin?<Link className="btn brandbtn" href={q({section:"more",area:"team",compose:"invite"})}><Icon name="plus"/> Inviter</Link>:undefined}/>
    {caregivers.length>0&&<Card tone="soft"><SectionHeader title="Voir comme" eyebrow="Contrôle parent"/><div className="v4-preview-people">{caregivers.filter(member=>previewableMemberIds.has(member.id)).map(member=><Link key={member.id} className="v4-preview-person" href={q({section:"today",preview:member.id})}><Avatar name={memberName(member)}/><span><strong>{memberName(member)}</strong><small>{roleLabel(member.role)}</small></span><Icon name="eye"/></Link>)}</div></Card>}
    {team.length?<div className="v4-grid-2">{team.map(member=>{const assigned=new Set(memberChildLinks.filter(link=>link.memberId===member.id).map(link=>link.childId));const configurable=canAdmin&&member.role!=="PARENT_ADMIN";const planningAllowed=member.permissions?.program!==false||member.permissions?.tasks!==false;return <Card key={member.id}><div className="v4-profile-hero"><Avatar name={memberName(member)} size="lg"/><div><h2>{memberName(member)}</h2><p>{roleLabel(member.role)}{member.label?` · ${member.label}`:""}</p></div></div><div className="v4-profile-chips">{children.filter(child=>assigned.has(child.id)).map(child=><StatusBadge key={child.id}>{child.firstName}</StatusBadge>)}</div>{!isParentRole(member.role)&&previewableMemberIds.has(member.id)&&<Link href={q({section:"today",preview:member.id})} className="btn soft full"><Icon name="eye"/> Voir comme {memberName(member)}</Link>}{configurable&&<details className="v4-profile-settings"><summary>Accès & attributions <Icon name="chevronRight" size={17}/></summary><form className="v4-form" action={updateMemberAccessAction}><input type="hidden" name="spaceId" value={spaceId}/><input type="hidden" name="memberId" value={member.id}/><div className="v4-field"><label>Enfants accessibles</label><div className="v4-check-grid">{children.map(child=><label className="v4-check-row" key={child.id}><input type="checkbox" name="childIds" value={child.id} defaultChecked={assigned.has(child.id)}/>{child.firstName}</label>)}</div></div><div className="v4-settings-group">{member.role==="PARENT"&&<label className="v4-setting-row"><span><strong>Gérer ses enfants</strong><small>Accès au profil et à l’organisation</small></span><span className="v4-switch"><input type="checkbox" name="children" defaultChecked={member.permissions?.children!==false}/><span/></span></label>}<PlanningSwitch defaultChecked={planningAllowed}/>{permissions.map(permission=><label className="v4-setting-row" key={permission.key}><span><strong>{permission.label}</strong><small>{permission.description}</small></span><span className="v4-switch"><input type="checkbox" name={permission.key} defaultChecked={member.permissions?.[permission.key]!==false}/><span/></span></label>)}</div><p className="v4-form-help">Planning regroupe activités et tâches. Si Courses est autorisé, le solde nécessaire à l’achat reste visible automatiquement.</p><button className="btn primary full">Enregistrer les accès</button></form></details>}</Card>})}</div>:<Card><EmptyState title="Aucun intervenant" description="Invitez une nounou, une baby-sitter ou un autre parent." icon="people"/></Card>}

    {canAdmin&&<Card><SectionHeader title="Semaine type" eyebrow="Horaires réguliers"/>{caregivers.map(member=><details className="v4-schedule-person" key={member.id}><summary><Avatar name={memberName(member)} size="sm"/><span>{memberName(member)}</span><Icon name="chevronRight"/></summary><div>{[[1,"Lun"],[2,"Mar"],[3,"Mer"],[4,"Jeu"],[5,"Ven"],[6,"Sam"],[0,"Dim"]].map(([weekday,label])=>{const rule=scheduleRules.find(candidate=>candidate.memberId===member.id&&candidate.weekday===weekday);return <form action={saveScheduleRuleAction} className="v4-schedule-row" key={weekday}><input type="hidden" name="spaceId" value={spaceId}/><input type="hidden" name="memberId" value={member.id}/><input type="hidden" name="weekday" value={weekday}/><label><input type="checkbox" name="active" defaultChecked={Boolean(rule)}/><strong>{label}</strong></label><input name="start" type="time" defaultValue={rule?.startTime||"16:00"}/><span>→</span><input name="end" type="time" defaultValue={rule?.endTime||"18:30"}/><button className="v4-icon-button" aria-label={`Enregistrer ${label}`}><Icon name="check"/></button></form>})}</div></details>)}<Link href={q({section:"more",area:"team",compose:"shift"})} className="btn soft full"><Icon name="calendar"/> Ajouter une garde ponctuelle</Link></Card>}

    {canAdmin&&invitations.length>0&&<Card><SectionHeader title="Invitations"/><div>{invitations.map(invitation=><div className="v4-list-row" key={invitation.id}><span className="v4-row-icon"><Icon name="people"/></span><span className="v4-row-copy"><strong>{invitation.email}</strong><small>{roleLabel(invitation.role)}</small></span><StatusBadge tone={invitation.status==="ACCEPTED"?"success":"neutral"}>{invitation.status}</StatusBadge>{invitation.status!=="ACCEPTED"&&<span className="v4-row-trailing"><form action={resendInvitationAction}><input type="hidden" name="spaceId" value={spaceId}/><input type="hidden" name="invitationId" value={invitation.id}/><button className="v4-icon-button" aria-label="Renvoyer"><Icon name="journal"/></button></form><form action={cancelInvitationAction}><input type="hidden" name="spaceId" value={spaceId}/><input type="hidden" name="invitationId" value={invitation.id}/><button className="v4-icon-button" aria-label="Annuler"><Icon name="close"/></button></form></span>}</div>)}</div></Card>}
    {compose==="invite"&&<InviteSheet spaceId={spaceId} children={children} q={q}/>} {compose==="shift"&&<ShiftSheet spaceId={spaceId} caregivers={caregivers} date={selectedDate} memberName={memberName} q={q}/>} 
  </div>;
}
