import Link from "next/link";
import type { members } from "@/db/schema";
import { spaceSnapshot } from "@/lib/data";
import { startShiftAction } from "@/app/actions/schedule";
import { endShiftAsPlannedFlexibleAction, endShiftWithFeedbackFlexibleAction } from "@/app/actions/shift-feedback";
import { Icon, type IconName } from "@/components/ui/icons";
import { Avatar, Card, EmptyState, SectionHeader, StatusBadge } from "@/components/ui/primitives";
import { activityIcon } from "@/lib/v4-presentation";
import type { CaregiverAgendaItem } from "@/lib/caregiver-agenda";
import { dateLabel, today } from "./utils";

type Snapshot=Awaited<ReturnType<typeof spaceSnapshot>>;type Member=typeof members.$inferSelect;type Query=(extra:Record<string,string>)=>string;type TimelineRow={id:string;kind:"program"|"task";time:string|null;title:string;subtitle:string;status:string;icon:IconName;plannedEnd?:string|null;note?:string|null};
function timeline(snapshot:Snapshot):TimelineRow[]{const program=snapshot.program.map(item=>({id:item.id,kind:"program" as const,time:item.plannedStart,title:item.title,subtitle:item.description||item.location||item.type,status:item.status,icon:activityIcon(item.type,item.title),plannedEnd:item.plannedEnd,note:item.note}));const tasks=snapshot.tasks.map(item=>({id:item.id,kind:"task" as const,time:item.time,title:item.title,subtitle:item.description||item.note||"",status:item.status,icon:activityIcon("tâche",item.title),note:item.note}));return [...program,...tasks].sort((a,b)=>(a.time||"99:99").localeCompare(b.time||"99:99"));}
function TimelineStatus({row}:{row:TimelineRow}){if(row.status==="DONE")return <StatusBadge tone="success">Fait</StatusBadge>;if(row.status==="NOT_DONE")return <StatusBadge tone={row.note?.startsWith("Remplacé par")?"brand":"neutral"}>{row.note?.startsWith("Remplacé par")?"Adapté":"Non fait"}</StatusBadge>;return <StatusBadge>Prévu</StatusBadge>}
export function Today({spaceId,selectedDate,snapshot,memberName,viewMembership,parent,preview,readOnly=false,q,fullTeam,userFirstName,timezone,globalAgenda=[]}:{spaceId:string;selectedDate:string;snapshot:Snapshot;memberName:(member:Member)=>string;actualMembership:Member;viewMembership:Member;parent:boolean;preview:boolean;readOnly?:boolean;q:Query;fullTeam:Member[];userFirstName:string;canActProgram:boolean;canActTasks:boolean;timezone:string;globalAgenda?:CaregiverAgendaItem[]}){
  const rows=timeline(snapshot);const unresolvedRows=rows.filter(row=>row.status!=="DONE"&&row.status!=="NOT_DONE");const important=snapshot.instructions.filter(item=>item.kind==="IMPORTANT"||item.kind==="FORBIDDEN"||item.kind==="ALLOWED");const visibleShifts=snapshot.shifts.filter(item=>item.status!=="CANCELLED");const activeShift=visibleShifts.find(item=>item.status==="ACTIVE")||visibleShifts.find(item=>item.status==="PLANNED")||visibleShifts[0];const shiftMember=(id:string)=>fullTeam.find(member=>member.id===id)||viewMembership;const next=unresolvedRows[0];const isToday=selectedDate===today(timezone);const parentView=parent&&!preview;const greeting=parentView?(userFirstName?`Bonjour ${userFirstName}`:"Bonjour"):`Bonjour ${memberName(viewMembership)}`;
  return <div className="v4-stack"><div className="v4-today-hero"><span className="v4-eyebrow">{dateLabel(selectedDate)}</span><h1>{greeting}</h1><p>{parentView?"Ce qui est prévu et ce qui s’est réellement passé aujourd’hui, au même endroit.":"Gardez le téléphone dans la poche : ajoutez seulement les moments utiles, même après coup."}</p>{visibleShifts.length>0&&<div className="v4-shift-strip">{visibleShifts.map(shift=>{const member=shiftMember(shift.memberId);return <div className="v4-shift-row" key={shift.id}><Avatar name={memberName(member)} size="sm"/><span className="v4-row-copy"><strong>{memberName(member)}</strong><small>{shift.plannedStart} → {shift.plannedEnd}{shift.status==="ACTIVE"?" · garde en cours":""}</small></span>{parentView?<Link className="v4-text-action" href={q({section:"planning",date:selectedDate,compose:"shift"})}>Modifier</Link>:shift.status==="ACTIVE"?<StatusBadge tone="success">En cours</StatusBadge>:null}</div>})}</div>}</div>
    {!parentView&&globalAgenda.length>1&&<Card tone="soft"><SectionHeader title="Toutes mes familles" eyebrow="Aujourd’hui"/><div className="v5-family-agenda">{globalAgenda.map(item=><Link href={`/app?space=${item.spaceId}&section=today`} key={item.spaceId} className={item.spaceId===spaceId?"is-active":""}><span><strong>{item.spaceName}</strong><small>{item.shift?`${item.shift.start} → ${item.shift.end}`:"Pas de garde prévue"}</small></span><span>{item.next?<><small>Ensuite</small><b>{item.next.time?`${item.next.time} · `:""}{item.next.title}</b></>:<small>Rien à faire</small>}</span></Link>)}</div></Card>}
    {next&&<Card tone="soft"><div className="v4-list-row"><span className="v4-row-icon"><Icon name={next.icon}/></span><span className="v4-row-copy"><small>Prochain</small><strong>{next.time?`${next.time} · `:""}{next.title}</strong>{next.subtitle&&<small>{next.subtitle}</small>}</span></div></Card>}
    <div className="v4-grid-2"><div className="v4-stack"><Card><SectionHeader title={parentView?"Aujourd’hui":"Ma journée"} eyebrow={rows.length?`${rows.length} repère${rows.length>1?"s":""}`:undefined} action={!parentView&&!preview&&!readOnly?<Link className="v4-text-action" href={q({section:"today",compose:"activity",activity:"moment"})}>+ Moment</Link>:undefined}/>{rows.length?<div className="v4-timeline">{rows.map(row=><div key={`${row.kind}-${row.id}`} className={`v4-timeline-item ${row.status==="DONE"?"is-done":""}`}><time className="v4-timeline-time">{row.time||"—"}</time><span className="v4-timeline-rail"><span className="v4-timeline-icon"><Icon name={row.icon} size={18}/></span></span>{row.kind==="program"&&parentView?<Link href={q({section:"today",compose:`activity-edit-${row.id}`})} className="v4-timeline-copy v4-activity-row-link"><strong>{row.title}</strong>{row.note&&row.status==="NOT_DONE"?<small>{row.note}</small>:row.subtitle&&<small>{row.subtitle}</small>}</Link>:<span className="v4-timeline-copy"><strong>{row.title}</strong>{row.note&&row.status==="NOT_DONE"?<small>{row.note}</small>:row.subtitle&&<small>{row.subtitle}</small>}</span>}<span className="v4-timeline-action"><TimelineStatus row={row}/></span></div>)}</div>:<EmptyState title="Rien de prévu aujourd’hui" description={parentView?"Le + permet d’ajouter un repère.":"Le + permet d’ajouter un moment, même plus tard dans la journée."}/>}</Card></div>
      <div className="v4-stack">{important.length>0&&<Card><SectionHeader title="À savoir aujourd’hui"/><div className="v4-instruction-list">{important.map(item=><div key={item.id} className={`v4-instruction ${item.kind==="FORBIDDEN"?"danger":item.kind==="IMPORTANT"?"warning":""}`}><Icon name={item.kind==="FORBIDDEN"?"ban":item.kind==="IMPORTANT"?"alert":"headphones"} size={18}/><span>{item.text}</span></div>)}</div></Card>}{snapshot.handovers.length>0&&<Card><SectionHeader title="À retenir" eyebrow="Fin de garde"/><div className="v4-stack">{snapshot.handovers.slice(0,3).map(handover=><div className="v4-list-row" key={handover.id}><span className="v4-row-icon"><Icon name="handover"/></span><span className="v4-row-copy"><strong>Retour de garde</strong><small>{handover.text}</small></span></div>)}</div></Card>}
      {!preview&&!readOnly&&!parent&&isToday&&activeShift&&activeShift.status!=="ENDED"&&<Card className="v51-shift-card" tone={activeShift.status==="ACTIVE"?"brand":"default"}><SectionHeader title="Ma garde" eyebrow={`${activeShift.plannedStart} → ${activeShift.plannedEnd}`}/><div className="v51-end-shift"><div className="v51-pocket-message"><Icon name="heart" size={20}/><span><strong>Aucun clic obligatoire</strong><small>Le début et le retour de fin de garde sont facultatifs. Vous pouvez simplement vivre la journée puis signaler uniquement ce qui est utile.</small></span></div>{activeShift.status==="PLANNED"&&<form action={startShiftAction}><input type="hidden" name="spaceId" value={spaceId}/><input type="hidden" name="shiftId" value={activeShift.id}/><button className="btn soft full">Signaler le début <span className="muted">· facultatif</span></button></form>}<form action={endShiftAsPlannedFlexibleAction}><input type="hidden" name="spaceId" value={spaceId}/><input type="hidden" name="shiftId" value={activeShift.id}/><button className="btn brandbtn full v51-one-tap"><Icon name="check" size={19}/> Tout s’est passé comme prévu</button></form><details className="v51-change-details"><summary><span><Icon name="note" size={18}/><strong>Il y a eu un changement</strong><small>Repas différent, sortie remplacée, activité en plus…</small></span><Icon name="chevronRight" size={17}/></summary><form action={endShiftWithFeedbackFlexibleAction} className="v4-form v51-feedback-form"><input type="hidden" name="spaceId" value={spaceId}/><input type="hidden" name="shiftId" value={activeShift.id}/>{unresolvedRows.length>0&&<div className="v51-feedback-list">{unresolvedRows.map(row=><fieldset className="v51-feedback-item" key={`${row.kind}-${row.id}`}><legend><span className="v4-timeline-icon"><Icon name={row.icon} size={17}/></span><span><strong>{row.title}</strong><small>{row.time||"Sans heure"}</small></span></legend><label>Ce qui s’est passé<select name={`outcome-${row.kind}-${row.id}`} defaultValue="AS_PLANNED"><option value="AS_PLANNED">Comme prévu</option><option value="NOTE">Fait, avec une précision</option><option value="NOT_DONE">Pas fait</option><option value="REPLACED">Remplacé par autre chose</option></select></label><label>Si remplacé<input name={`replacement-${row.kind}-${row.id}`} placeholder="Ex. Escalade, omelette…" maxLength={80}/></label><label>Petit retour <span className="muted">· facultatif</span><textarea name={`feedback-${row.kind}-${row.id}`} rows={2} placeholder="Ex. Elle n’a pas mangé les brocolis."/></label></fieldset>)}</div>}<div className="v4-field"><label>À retenir <span className="muted">· facultatif</span></label><textarea name="handover" rows={3} placeholder="Une information générale pour les parents…"/></div><button className="btn primary full">Enregistrer le retour</button></form></details><small className="muted">Vous pouvez aussi ne rien faire si vous n’avez rien à transmettre.</small></div></Card>}</div></div>
  </div>;
}
