import Link from "next/link";
import type { notifications as notificationsTable } from "@/db/schema";
import { markAllNotificationsReadAction, openNotificationAction } from "@/app/actions/notifications";
import { notificationCategory } from "@/lib/notification-center";
import { Icon, type IconName } from "@/components/ui/icons";

type Notification=typeof notificationsTable.$inferSelect;
function notificationIcon(type:string):IconName{const category=notificationCategory(type);if(category==="message")return "journal";if(category==="handover")return "handover";if(category==="activity")return "activity";if(category==="shift")return "clock";return "bell";}
function dateTime(value:Date){return new Intl.DateTimeFormat("fr-FR",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value));}
export function NotificationBell({items,unreadCount,spaceNames,settingsHref}:{items:Notification[];unreadCount:number;spaceNames:Record<string,string>;settingsHref:string}){
  return <details className="v54-notifications"><summary className="v54-notification-trigger" aria-label={unreadCount?`${unreadCount} notification${unreadCount>1?"s":""} non lue${unreadCount>1?"s":""}`:"Notifications"}><Icon name="bell" size={20}/>{unreadCount>0&&<span className="v54-notification-badge">{unreadCount>9?"9+":unreadCount}</span>}</summary><div className="v54-notification-panel"><header><span><strong>Notifications</strong><small>{unreadCount?`${unreadCount>9?"9+":unreadCount} à lire`:"Vous êtes à jour"}</small></span>{unreadCount>0&&<form action={markAllNotificationsReadAction}><button>Tout marquer comme lu</button></form>}</header>{items.length?<div className="v54-notification-list">{items.map(item=><form action={openNotificationAction} key={item.id}><input type="hidden" name="notificationId" value={item.id}/><button className={`v54-notification-item ${item.readAt?"":"is-unread"}`}><span className="v54-notification-icon"><Icon name={notificationIcon(item.type)} size={17}/></span><span className="v54-notification-copy"><span className="v54-notification-meta"><b>{spaceNames[item.careSpaceId]||"Famille"}</b><time>{dateTime(item.createdAt)}</time></span><strong>{item.title}</strong>{item.body&&<small>{item.body}</small>}</span>{!item.readAt&&<i className="v54-unread-dot"/>}</button></form>)}</div>:<div className="v54-notification-empty"><Icon name="bell" size={22}/><strong>Rien de nouveau</strong><small>Les messages et moments importants apparaîtront ici.</small></div>}<footer><Link href={settingsHref}>Réglages des notifications</Link></footer></div></details>;
}
